export { createDistributedReplica } from './distributed-replica.js';
export { replicaIndexKey, replicaRecordKey } from './identity.js';
export type {
	DistributedReplicaOptions,
	DistributedReplica,
	ReplicaArgumentsArtifact,
	ReplicaArgumentValue,
	ReplicaBaseWriter,
	ReplicaBranchSemantic,
	ReplicaCoverageArtifact,
	ReplicaEntitySelection,
	ReplicaIdentity,
	ReplicaIndexCoverage,
	ReplicaIndexInspection,
	ReplicaIndexTarget,
	ReplicaLiveObserver,
	ReplicaLiveState,
	ReplicaLiteralValue,
	ReplicaModelArtifact,
	ReplicaObjectBranch,
	ReplicaObjectMember,
	ReplicaObjectSelection,
	ReplicaOperationArtifact,
	ReplicaOptimisticWriter,
	ReplicaRecordInspection,
	ReplicaRecordPatch,
	ReplicaRevision,
	ReplicaRelationshipSelection,
	ReplicaResultEnvelope,
	ReplicaRootSelection,
	ReplicaScalarSelection,
	ReplicaSelectionStorage,
	ReplicaSparse,
	ReplicaSnapshot,
	ReplicaStatus,
	ReplicaTransport,
	ReplicaTransportRequest,
	ReplicaVariableValue,
	ReplicaValue,
	ReplicaWatch,
	ReplicaWriteSource,
	WatchReplicaOptions
} from './types.js';
