export type CommandManifestField = {
  name: string;
  type_name: string;
  nullable: boolean;
  list: boolean;
};

export type CommandManifestType = {
  name: string;
  fields: CommandManifestField[];
};

export type CommandResultKind = 'ack' | 'fact' | 'projection' | 'none';
export type CommandReconcileKind =
  | 'subscription'
  | 'refetch'
  | 'invalidate'
  | 'none';

export type CommandManifestEntry = {
  command_name: string;
  field_name: string;
  roles: string[];
  input?: CommandManifestType;
  output?: CommandManifestType;
  client_reconcile?: {
    result?: { kind: CommandResultKind };
    reconcile?: { kind: CommandReconcileKind };
  };
};

export type CommandManifestV1 = {
  version: 1;
  commands: CommandManifestEntry[];
};

export type GeneratedCommandArtifacts = {
  commands: string;
  operations: string;
  policies: string;
};

export type GeneratePoliciesOptions = {
  /** NodeNext import from the generated policies module to the commands module. */
  commandsImport?: string;
};

const GRAPHQL_NAME = /^[_A-Za-z][_0-9A-Za-z]*$/;
const TYPESCRIPT_RESERVED = new Set([
  'any',
  'as',
  'asserts',
  'async',
  'await',
  'bigint',
  'boolean',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'constructor',
  'continue',
  'debugger',
  'declare',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'from',
  'function',
  'get',
  'if',
  'implements',
  'import',
  'in',
  'infer',
  'instanceof',
  'interface',
  'is',
  'keyof',
  'let',
  'module',
  'namespace',
  'never',
  'new',
  'null',
  'number',
  'object',
  'of',
  'package',
  'private',
  'protected',
  'public',
  'readonly',
  'require',
  'return',
  'set',
  'static',
  'string',
  'super',
  'switch',
  'symbol',
  'this',
  'throw',
  'true',
  'try',
  'type',
  'typeof',
  'undefined',
  'unique',
  'unknown',
  'var',
  'void',
  'while',
  'with',
  'yield'
]);
const RESULT_KINDS = new Set<CommandResultKind>([
  'ack',
  'fact',
  'projection',
  'none'
]);
const RECONCILE_KINDS = new Set<CommandReconcileKind>([
  'subscription',
  'refetch',
  'invalidate',
  'none'
]);
const MANIFEST_V1_SCALAR_TYPES = new Set([
  'String',
  'ID',
  'Boolean',
  'Int',
  'Float',
  'BigInt',
  'JSON'
]);

/** Validate and normalize a Distributed command manifest (format version 1). */
export function parseCommandManifest(value: unknown): CommandManifestV1 {
  const root = expectRecord(value, 'manifest');
  if (root.version !== 1) {
    throw new Error('invalid command manifest: expected version 1');
  }
  if (!Array.isArray(root.commands)) {
    throw new Error('invalid command manifest: commands must be an array');
  }

  const commands = root.commands.map((entry, index) => parseCommand(entry, index));
  const fields = new Set<string>();
  const functions = new Set<string>();
  for (const command of commands) {
    if (fields.has(command.field_name)) {
      throw new Error(`invalid command manifest: duplicate field ${command.field_name}`);
    }
    fields.add(command.field_name);

    const functionName = fieldToFunctionName(command.field_name);
    if (TYPESCRIPT_RESERVED.has(functionName)) {
      throw new Error(
        `invalid command manifest: field ${command.field_name} maps to reserved TypeScript name ${functionName}`
      );
    }
    if (functions.has(functionName)) {
      throw new Error(
        `invalid command manifest: fields collide at function ${functionName}`
      );
    }
    functions.add(functionName);
  }
  assertCompatibleTypeDefinitions(commands);

  return { version: 1, commands };
}

/** Build one mutation document from a normalized command entry. */
export function buildMutationOperation(command: CommandManifestEntry): string {
  const operationName = `Command_${command.field_name}`;
  const selection = command.output?.fields.map((field) => field.name) ?? [];
  const fieldStart = command.input
    ? `  ${command.field_name}(input: $input)`
    : `  ${command.field_name}`;
  const fieldLines = selection.length
    ? [
        `${fieldStart} {`,
        ...selection.map((field) => `    ${field}`),
        '  }'
      ]
    : [fieldStart];

  return command.input
    ? [
        `mutation ${operationName}($input: ${command.input.name}!) {`,
        ...fieldLines,
        '}'
      ].join('\n')
    : [`mutation ${operationName} {`, ...fieldLines, '}'].join('\n');
}

/** Generate copy-pasteable GraphQL operations for the whole manifest. */
export function generateOperationsGql(value: CommandManifestV1 | unknown): string {
  const manifest = parseCommandManifest(value);
  const lines = [
    '# GENERATED by @hops-ops/distributed — do not edit by hand.',
    '# Source: commands.manifest.json',
    '# Regenerate with: distributed-gen-commands',
    ''
  ];

  for (const command of manifest.commands) {
    const roles = command.roles.length
      ? command.roles.map((role) => JSON.stringify(role)).join(', ')
      : '(any)';
    lines.push(`# ${JSON.stringify(command.command_name)} — roles: ${roles}`);
    lines.push(buildMutationOperation(command));
    lines.push('');
  }

  return withFinalNewline(lines.join('\n'));
}

/** Generate typed descriptors, standalone calls, and a single bound command API. */
export function generateCommandsTs(value: CommandManifestV1 | unknown): string {
  const manifest = parseCommandManifest(value);
  const lines: string[] = [
    '/**',
    ' * GENERATED by @hops-ops/distributed — do not edit by hand.',
    ' * Source: commands.manifest.json',
    ' * Regenerate with: distributed-gen-commands',
    ' */',
    'import {',
    '  bindCommands as bindDistributedCommands,',
    '  defineCommand,',
    '  defineCommands,',
    '  executeCommand,',
    '  type BindCommandsOptions,',
    '  type BoundCommandSet,',
    '  type CommandClient,',
    '  type GqlResult',
    "} from '@hops-ops/distributed';",
    ''
  ];

  for (const definition of collectTypeDefinitions(manifest.commands)) {
    lines.push(`export type ${definition.name} = {`);
    for (const field of definition.fields) {
      const optional = field.nullable ? '?' : '';
      const nullable = field.nullable ? ' | null' : '';
      lines.push(
        `  ${field.name}${optional}: ${manifestFieldToTs(field)}${nullable};`
      );
    }
    lines.push('};', '');
  }

  lines.push(
    '/** Field name to engine roles. Client metadata is not an authorization boundary. */',
    'export const COMMAND_ROLES = {'
  );
  for (const command of manifest.commands) {
    const roles = command.roles.map((role) => JSON.stringify(role)).join(', ');
    lines.push(`  ${JSON.stringify(command.field_name)}: [${roles}] as const,`);
  }
  lines.push('} as const;', '');

  lines.push(
    '/** Mutation documents mirrored in commands.operations.gql. */',
    'export const COMMAND_DOCS = {'
  );
  for (const command of manifest.commands) {
    lines.push(`  ${JSON.stringify(command.field_name)}: \``);
    for (const line of buildMutationOperation(command).split('\n')) {
      lines.push(escapeTemplateLiteralLine(line));
    }
    lines.push('`,');
  }
  lines.push('} as const;', '');

  lines.push('/** Typed command descriptors consumed by the package runtime. */');
  lines.push('export const COMMANDS = defineCommands({');
  for (const command of manifest.commands) {
    const functionName = fieldToFunctionName(command.field_name);
    const inputType = command.input?.name ?? 'void';
    const outputType = command.output?.name ?? 'unknown';
    lines.push(
      `  ${functionName}: defineCommand<${inputType}, ${outputType}>({`,
      `    field: ${JSON.stringify(command.field_name)},`,
      `    document: COMMAND_DOCS[${JSON.stringify(command.field_name)}],`,
      `    hasInput: ${command.input ? 'true' : 'false'},`,
      `    roles: COMMAND_ROLES[${JSON.stringify(command.field_name)}]`,
      '  }),'
    );
  }
  lines.push('});', '');

  for (const command of manifest.commands) {
    const functionName = fieldToFunctionName(command.field_name);
    const outputType = command.output?.name ?? 'unknown';
    lines.push('/**');
    lines.push(
      ` * ${commentLine(command.command_name)} -> GraphQL \`${command.field_name}\`.`
    );
    lines.push(' */');
    if (command.input) {
      lines.push(
        `export function ${functionName}(input: ${command.input.name}, client: CommandClient): Promise<GqlResult<${outputType}>> {`,
        `  return executeCommand(client, COMMANDS.${functionName}, input);`,
        '}',
        ''
      );
    } else {
      lines.push(
        `export function ${functionName}(client: CommandClient): Promise<GqlResult<${outputType}>> {`,
        `  return executeCommand(client, COMMANDS.${functionName});`,
        '}',
        ''
      );
    }
  }

  lines.push(
    '/** Commands pre-bound to a GraphQL client, with optional per-call policies. */',
    'export type BoundCommands = BoundCommandSet<typeof COMMANDS>;',
    'export type CommandBindOptions = BindCommandsOptions<typeof COMMANDS>;',
    '',
    '/** Bind URL/auth/cache once, then call `commands.someCommand(input, options?)`. */',
    'export function bindCommands(',
    '  client: CommandClient,',
    '  options: CommandBindOptions = {}',
    '): BoundCommands {',
    '  return bindDistributedCommands(client, COMMANDS, options);',
    '}',
    ''
  );

  return withFinalNewline(lines.join('\n'));
}

/** Generate default client policies from manifest reconciliation hints. */
export function generateCommandPoliciesTs(
  value: CommandManifestV1 | unknown,
  options: GeneratePoliciesOptions = {}
): string {
  const manifest = parseCommandManifest(value);
  const commandsImport = options.commandsImport ?? './commands.generated.js';
  if (!isRelativeNodeImport(commandsImport)) {
    throw new Error(
      'commandsImport must be a relative NodeNext specifier ending in .js, .mjs, or .cjs'
    );
  }

  const lines: string[] = [
    '/**',
    ' * GENERATED by @hops-ops/distributed — do not edit by hand.',
    ' * Source: commands.manifest.json client_reconcile hints',
    ' * Regenerate with: distributed-gen-commands',
    ' */',
    "import type { CommandPolicyMap } from '@hops-ops/distributed';",
    `import type { COMMANDS } from ${JSON.stringify(commandsImport)};`,
    '',
    '/** Call-site options override these generated defaults. */',
    'export const commandPolicies = {'
  ];

  for (const command of manifest.commands) {
    const client = command.client_reconcile;
    if (!client?.result && !client?.reconcile) continue;
    const functionName = fieldToFunctionName(command.field_name);
    lines.push(`  ${functionName}: {`);
    if (client.result) {
      lines.push(`    result: { kind: ${JSON.stringify(client.result.kind)} },`);
    }
    if (client.reconcile) {
      lines.push(
        `    reconcile: { kind: ${JSON.stringify(client.reconcile.kind)} },`
      );
    }
    lines.push('  },');
  }

  lines.push('} satisfies CommandPolicyMap<typeof COMMANDS>;', '');
  return withFinalNewline(lines.join('\n'));
}

/** Generate all three app-owned artifacts from one validated manifest. */
export function generateCommandArtifacts(
  value: CommandManifestV1 | unknown,
  options: GeneratePoliciesOptions = {}
): GeneratedCommandArtifacts {
  const manifest = parseCommandManifest(value);
  return {
    commands: generateCommandsTs(manifest),
    operations: generateOperationsGql(manifest),
    policies: generateCommandPoliciesTs(manifest, options)
  };
}

/** Convert a GraphQL field name such as `todos_create` to `todosCreate`. */
export function fieldToFunctionName(field: string): string {
  return field.replace(/_([A-Za-z0-9])/g, (_match, character: string) =>
    character.toUpperCase()
  );
}

function parseCommand(value: unknown, index: number): CommandManifestEntry {
  const path = `manifest.commands[${index}]`;
  const command = expectRecord(value, path);
  const commandName = expectNonEmptyString(command.command_name, `${path}.command_name`);
  const fieldName = expectGraphqlName(command.field_name, `${path}.field_name`);
  const roles = command.roles === undefined ? [] : parseRoles(command.roles, `${path}.roles`);
  const input =
    command.input === null || command.input === undefined
      ? undefined
      : parseManifestType(command.input, `${path}.input`);
  const output =
    command.output === null || command.output === undefined
      ? undefined
      : parseManifestType(command.output, `${path}.output`);
  const clientReconcile =
    command.client_reconcile === null || command.client_reconcile === undefined
      ? undefined
      : parseClientReconcile(command.client_reconcile, `${path}.client_reconcile`);

  return {
    command_name: commandName,
    field_name: fieldName,
    roles,
    ...(input ? { input } : {}),
    ...(output ? { output } : {}),
    ...(clientReconcile ? { client_reconcile: clientReconcile } : {})
  };
}

function parseManifestType(value: unknown, path: string): CommandManifestType {
  const type = expectRecord(value, path);
  const name = expectGraphqlName(type.name, `${path}.name`);
  if (TYPESCRIPT_RESERVED.has(name)) {
    throw new Error(`invalid command manifest: ${path}.name is reserved in TypeScript`);
  }
  if (!Array.isArray(type.fields)) {
    throw new Error(`invalid command manifest: ${path}.fields must be an array`);
  }

  const names = new Set<string>();
  const fields = type.fields.map((field, index) => {
    const fieldPath = `${path}.fields[${index}]`;
    const record = expectRecord(field, fieldPath);
    const fieldName = expectGraphqlName(record.name, `${fieldPath}.name`);
    if (names.has(fieldName)) {
      throw new Error(`invalid command manifest: duplicate field ${path}.${fieldName}`);
    }
    names.add(fieldName);
    const typeName = expectGraphqlName(record.type_name, `${fieldPath}.type_name`);
    if (!MANIFEST_V1_SCALAR_TYPES.has(typeName)) {
      throw new Error(
        `invalid command manifest: ${fieldPath}.type_name ${JSON.stringify(typeName)} is unsupported; manifest version 1 can only generate scalar fields (${[...MANIFEST_V1_SCALAR_TYPES].join(', ')}). Nested objects, enums, and custom scalars require explicit type metadata in a future manifest version`
      );
    }
    return {
      name: fieldName,
      type_name: typeName,
      nullable: expectBoolean(record.nullable, `${fieldPath}.nullable`),
      list: expectBoolean(record.list, `${fieldPath}.list`)
    };
  });

  return { name, fields };
}

function parseRoles(value: unknown, path: string): string[] {
  if (!Array.isArray(value)) {
    throw new Error(`invalid command manifest: ${path} must be an array`);
  }
  return value.map((role, index) =>
    expectNonEmptyString(role, `${path}[${index}]`)
  );
}

function parseClientReconcile(
  value: unknown,
  path: string
): NonNullable<CommandManifestEntry['client_reconcile']> {
  const client = expectRecord(value, path);
  let result: { kind: CommandResultKind } | undefined;
  let reconcile: { kind: CommandReconcileKind } | undefined;

  if (client.result !== null && client.result !== undefined) {
    const record = expectRecord(client.result, `${path}.result`);
    const kind = expectNonEmptyString(record.kind, `${path}.result.kind`);
    if (!RESULT_KINDS.has(kind as CommandResultKind)) {
      throw new Error(`invalid command manifest: unsupported result kind ${kind}`);
    }
    result = { kind: kind as CommandResultKind };
  }

  if (client.reconcile !== null && client.reconcile !== undefined) {
    const record = expectRecord(client.reconcile, `${path}.reconcile`);
    const kind = expectNonEmptyString(record.kind, `${path}.reconcile.kind`);
    if (!RECONCILE_KINDS.has(kind as CommandReconcileKind)) {
      throw new Error(`invalid command manifest: unsupported reconcile kind ${kind}`);
    }
    reconcile = { kind: kind as CommandReconcileKind };
  }

  return {
    ...(result ? { result } : {}),
    ...(reconcile ? { reconcile } : {})
  };
}

function collectTypeDefinitions(commands: CommandManifestEntry[]): CommandManifestType[] {
  const types = new Map<string, CommandManifestType>();
  for (const command of commands) {
    if (command.input && !types.has(command.input.name)) {
      types.set(command.input.name, command.input);
    }
    if (command.output && !types.has(command.output.name)) {
      types.set(command.output.name, command.output);
    }
  }
  return [...types.values()];
}

function assertCompatibleTypeDefinitions(commands: CommandManifestEntry[]): void {
  const definitions = new Map<string, string>();
  for (const type of collectAllTypeDefinitions(commands)) {
    const shape = JSON.stringify(type.fields);
    const existing = definitions.get(type.name);
    if (existing !== undefined && existing !== shape) {
      throw new Error(
        `invalid command manifest: conflicting definitions for type ${type.name}`
      );
    }
    definitions.set(type.name, shape);
  }
}

function collectAllTypeDefinitions(commands: CommandManifestEntry[]): CommandManifestType[] {
  return commands.flatMap((command) =>
    [command.input, command.output].filter(
      (type): type is CommandManifestType => type !== undefined
    )
  );
}

function manifestFieldToTs(field: CommandManifestField): string {
  let type: string;
  switch (field.type_name) {
    case 'String':
    case 'ID':
      type = 'string';
      break;
    case 'Boolean':
      type = 'boolean';
      break;
    case 'Int':
    case 'Float':
    case 'BigInt':
      type = 'number';
      break;
    case 'JSON':
      type = 'unknown';
      break;
    default:
      type = field.type_name;
  }
  return field.list ? `Array<${type}>` : type;
}

function expectRecord(value: unknown, path: string): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`invalid command manifest: ${path} must be an object`);
  }
  return value as Record<string, unknown>;
}

function expectNonEmptyString(value: unknown, path: string): string {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`invalid command manifest: ${path} must be a non-empty string`);
  }
  return value;
}

function expectGraphqlName(value: unknown, path: string): string {
  const name = expectNonEmptyString(value, path);
  if (!GRAPHQL_NAME.test(name)) {
    throw new Error(`invalid command manifest: ${path} is not a GraphQL name`);
  }
  return name;
}

function expectBoolean(value: unknown, path: string): boolean {
  if (typeof value !== 'boolean') {
    throw new Error(`invalid command manifest: ${path} must be a boolean`);
  }
  return value;
}

function escapeTemplateLiteralLine(line: string): string {
  return line
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

function commentLine(value: string): string {
  return value
    .replace(/[\r\n\u2028\u2029]+/g, ' ')
    .replace(/\*\//g, '*\\/')
    .trim();
}

function withFinalNewline(value: string): string {
  return `${value.replace(/\n+$/g, '')}\n`;
}

function isRelativeNodeImport(value: string): boolean {
  return (
    (value.startsWith('./') || value.startsWith('../')) &&
    /\.(?:c|m)?js$/.test(value)
  );
}
