[package]
name = "workshop-readmodels"
version.workspace = true
edition.workspace = true
publish = false
description = "Shared read models for catalog + orders BCs"

[dependencies]
distributed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
workshop-catalog-domain = { path = "../catalog-domain" }
workshop-orders-domain = { path = "../orders-domain" }
