use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Component, Path, PathBuf};

const INVENTORY_PATH: &str = "migrations/inventory.json";
const INVENTORY_VERSION: u32 = 1;
const MAX_INVENTORY_BYTES: usize = 1024 * 1024;
const MAX_SQL_BYTES: usize = 4 * 1024 * 1024;
const MAX_MIGRATIONS: usize = 256;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Inventory {
    schema_version: u32,
    migrations: Vec<Migration>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Migration {
    version: u64,
    description: String,
    sqlite: MigrationFile,
    postgres: MigrationFile,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct MigrationFile {
    path: String,
    sha256: String,
}

#[derive(Clone, Copy)]
enum Dialect {
    Sqlite,
    Postgres,
}

impl Dialect {
    const ALL: [Self; 2] = [Self::Sqlite, Self::Postgres];

    const fn name(self) -> &'static str {
        match self {
            Self::Sqlite => "sqlite",
            Self::Postgres => "postgres",
        }
    }

    const fn directory(self) -> &'static str {
        match self {
            Self::Sqlite => "migrations/sqlite",
            Self::Postgres => "migrations/postgres",
        }
    }

    fn file(self, migration: &Migration) -> &MigrationFile {
        match self {
            Self::Sqlite => &migration.sqlite,
            Self::Postgres => &migration.postgres,
        }
    }
}

fn main() {
    emit_migration_inventory();

    // Only run gRPC codegen when the "grpc" feature is enabled.
    // Cargo sets CARGO_FEATURE_GRPC when compiling with --features grpc.
    if std::env::var("CARGO_FEATURE_GRPC").is_ok() {
        let service = tonic_build::manual::Service::builder()
            .name("CommandService")
            .package("sourced.microsvc")
            .method(
                tonic_build::manual::Method::builder()
                    .name("dispatch")
                    .route_name("Dispatch")
                    .input_type("crate::microsvc::grpc::GrpcRequest")
                    .output_type("crate::microsvc::grpc::GrpcResponse")
                    .codec_path("tonic_prost::ProstCodec")
                    .build(),
            )
            .method(
                tonic_build::manual::Method::builder()
                    .name("health")
                    .route_name("Health")
                    .input_type("crate::microsvc::grpc::HealthRequest")
                    .output_type("crate::microsvc::grpc::HealthResponse")
                    .codec_path("tonic_prost::ProstCodec")
                    .build(),
            )
            .build();

        tonic_build::manual::Builder::new().compile(&[service]);
    }
}

fn emit_migration_inventory() {
    println!("cargo:rerun-if-changed={INVENTORY_PATH}");
    for dialect in Dialect::ALL {
        // Watching the dialect roots also notices an unregistered SQL file
        // being added; the explicit file lines below keep declared inputs
        // visible in Cargo's build explanation.
        println!("cargo:rerun-if-changed={}", dialect.directory());
    }
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR")
            .expect("Cargo must provide CARGO_MANIFEST_DIR to the build script"),
    );
    let root = fs::canonicalize(&manifest_dir)
        .unwrap_or_else(|error| panic!("resolve repository root for migrations: {error}"));
    let inventory_path = root.join(INVENTORY_PATH);
    let bytes = read_bounded_file(&inventory_path, MAX_INVENTORY_BYTES, "migration inventory");
    let inventory: Inventory = serde_json::from_slice(&bytes)
        .unwrap_or_else(|error| panic!("parse {INVENTORY_PATH}: {error}"));
    validate_inventory(&root, &inventory);

    for migration in &inventory.migrations {
        for dialect in Dialect::ALL {
            println!("cargo:rerun-if-changed={}", dialect.file(migration).path);
        }
    }

    let out_dir = PathBuf::from(
        std::env::var_os("OUT_DIR").expect("Cargo must provide OUT_DIR to the build script"),
    );
    let generated_path = out_dir.join("migration_inventory.rs");
    let mut generated =
        String::from("// Generated by build.rs from migrations/inventory.json; do not edit.\n");
    emit_dialect(
        &mut generated,
        "SQLITE_MIGRATIONS",
        Dialect::Sqlite,
        &inventory,
    );
    emit_dialect(
        &mut generated,
        "POSTGRES_MIGRATIONS",
        Dialect::Postgres,
        &inventory,
    );
    let mut file = File::create(&generated_path)
        .unwrap_or_else(|error| panic!("create generated migration registration: {error}"));
    file.write_all(generated.as_bytes())
        .unwrap_or_else(|error| panic!("write generated migration registration: {error}"));
}

fn emit_dialect(generated: &mut String, name: &str, dialect: Dialect, inventory: &Inventory) {
    generated.push_str("#[cfg(feature = \"");
    generated.push_str(dialect.name());
    generated.push_str("\")]\n");
    generated.push_str("pub(crate) const ");
    generated.push_str(name);
    generated.push_str(": &[EmbeddedMigration] = &[\n");
    for migration in &inventory.migrations {
        let file = dialect.file(migration);
        generated.push_str("    EmbeddedMigration { version: ");
        generated.push_str(&migration.version.to_string());
        generated.push_str(", description: ");
        generated.push_str(&format!("{:?}", migration.description));
        generated.push_str(", sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", ");
        generated.push_str(&format!("{:?}", file.path));
        generated.push_str(")), },\n");
    }
    generated.push_str("];\n");
}

fn validate_inventory(root: &Path, inventory: &Inventory) {
    if inventory.schema_version != INVENTORY_VERSION {
        panic!(
            "{INVENTORY_PATH} schema version {} is unsupported; expected {INVENTORY_VERSION}",
            inventory.schema_version
        );
    }
    if inventory.migrations.is_empty() || inventory.migrations.len() > MAX_MIGRATIONS {
        panic!("{INVENTORY_PATH} must contain 1..={MAX_MIGRATIONS} migrations");
    }
    let mut paths = BTreeMap::new();
    for (index, migration) in inventory.migrations.iter().enumerate() {
        let expected = (index + 1) as u64;
        if migration.version != expected {
            panic!(
                "{INVENTORY_PATH} versions must be consecutive: expected {expected}, observed {}",
                migration.version
            );
        }
        if migration.version > i64::MAX as u64
            || migration.description.is_empty()
            || migration.description.trim() != migration.description
        {
            panic!(
                "{INVENTORY_PATH} migration {} has an invalid description or version",
                migration.version
            );
        }
        for dialect in Dialect::ALL {
            let file = dialect.file(migration);
            validate_path(root, dialect, file);
            if file.sha256.len() != 64
                || !file.sha256.bytes().all(|byte| byte.is_ascii_hexdigit())
                || file
                    .sha256
                    .chars()
                    .any(|character| character.is_ascii_uppercase())
            {
                panic!(
                    "{INVENTORY_PATH} {} migration `{}` has an invalid SHA-256",
                    dialect.name(),
                    file.path
                );
            }
            if paths
                .insert(file.path.clone(), (migration.version, dialect.name()))
                .is_some()
            {
                panic!(
                    "{INVENTORY_PATH} migration path `{}` is declared more than once",
                    file.path
                );
            }
            let sql_path = root.join(&file.path);
            let sql = read_bounded_file(&sql_path, MAX_SQL_BYTES, "migration SQL");
            if std::str::from_utf8(&sql).is_err() {
                panic!("migration SQL `{}` is not UTF-8", file.path);
            }
            let observed = sha256_hex(&sql);
            if observed != file.sha256 {
                panic!(
                    "{INVENTORY_PATH} {} migration `{}` checksum mismatch: expected {}, observed {}",
                    dialect.name(),
                    file.path,
                    file.sha256,
                    observed
                );
            }
        }
    }
    for dialect in Dialect::ALL {
        let actual = collect_sql_files(root, dialect);
        for path in actual.keys() {
            if !paths.contains_key(path) {
                panic!(
                    "{INVENTORY_PATH} extra {} migration file `{path}` is not registered",
                    dialect.name()
                );
            }
        }
    }
    validate_dialect_directories(root);
}

fn validate_path(root: &Path, dialect: Dialect, file: &MigrationFile) {
    let path = Path::new(&file.path);
    if file.path.is_empty()
        || file.path.trim() != file.path
        || file.path.contains('\\')
        || !file.path.ends_with(".sql")
        || path.is_absolute()
        || path
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
        || !path.starts_with(dialect.directory())
    {
        panic!(
            "{INVENTORY_PATH} {} migration path `{}` is outside `{}`",
            dialect.name(),
            file.path,
            dialect.directory()
        );
    }
    let mut current = root.to_path_buf();
    for component in path.components() {
        let Component::Normal(component) = component else {
            unreachable!("validated migration path components");
        };
        current.push(component);
        let metadata = fs::symlink_metadata(&current)
            .unwrap_or_else(|error| panic!("inspect migration path `{}`: {error}", file.path));
        if metadata.file_type().is_symlink() {
            panic!("migration path `{}` must not be a symlink", file.path);
        }
    }
}

fn read_bounded_file(path: &Path, limit: usize, label: &str) -> Vec<u8> {
    let metadata = fs::symlink_metadata(path)
        .unwrap_or_else(|error| panic!("read {label} `{}`: {error}", path.display()));
    if metadata.file_type().is_symlink() {
        panic!("{label} `{}` must not be a symlink", path.display());
    }
    if !metadata.is_file() {
        panic!("{label} `{}` is not a regular file", path.display());
    }
    if metadata.len() > limit as u64 {
        panic!("{label} `{}` exceeds {limit} bytes", path.display());
    }
    let file = File::open(path)
        .unwrap_or_else(|error| panic!("read {label} `{}`: {error}", path.display()));
    let opened_size = file
        .metadata()
        .unwrap_or_else(|error| panic!("inspect {label} `{}`: {error}", path.display()))
        .len();
    if opened_size > limit as u64 {
        panic!("opened {label} `{}` exceeds {limit} bytes", path.display());
    }
    let mut bytes = Vec::with_capacity(opened_size as usize);
    file.take(limit as u64 + 1)
        .read_to_end(&mut bytes)
        .unwrap_or_else(|error| panic!("read {label} `{}`: {error}", path.display()));
    if bytes.len() > limit {
        panic!("{label} `{}` exceeds {limit} bytes", path.display());
    }
    bytes
}

fn collect_sql_files(root: &Path, dialect: Dialect) -> BTreeMap<String, ()> {
    let mut pending = vec![root.join(dialect.directory())];
    let mut files = BTreeMap::new();
    while let Some(directory) = pending.pop() {
        let directory_metadata = fs::symlink_metadata(&directory).unwrap_or_else(|error| {
            panic!(
                "inspect migration directory `{}`: {error}",
                directory.display()
            )
        });
        if directory_metadata.file_type().is_symlink() {
            panic!(
                "migration directory `{}` must not be a symlink",
                directory.display()
            );
        }
        if !directory_metadata.is_dir() {
            panic!(
                "migration directory `{}` is not a directory",
                directory.display()
            );
        }
        let entries = fs::read_dir(&directory).unwrap_or_else(|error| {
            panic!(
                "read migration directory `{}`: {error}",
                directory.display()
            )
        });
        let mut entries = entries
            .collect::<Result<Vec<_>, _>>()
            .unwrap_or_else(|error| panic!("read migration directory: {error}"));
        entries.sort_by_key(|entry| entry.file_name());
        for entry in entries {
            let path = entry.path();
            let metadata = fs::symlink_metadata(&path).unwrap_or_else(|error| {
                panic!("inspect migration path `{}`: {error}", path.display())
            });
            if metadata.file_type().is_symlink() {
                panic!("migration path `{}` must not be a symlink", path.display());
            }
            if metadata.is_dir() {
                pending.push(path);
                continue;
            }
            if !metadata.is_file() {
                panic!("migration path `{}` is not a regular file", path.display());
            }
            if path.extension().and_then(|extension| extension.to_str()) != Some("sql") {
                continue;
            }
            let relative = path
                .strip_prefix(root)
                .unwrap_or_else(|_| {
                    panic!(
                        "migration path `{}` escaped repository root",
                        path.display()
                    )
                })
                .to_string_lossy()
                .replace(std::path::MAIN_SEPARATOR, "/");
            files.insert(relative, ());
        }
    }
    files
}

fn validate_dialect_directories(root: &Path) {
    let migrations = root.join("migrations");
    let migrations_metadata = fs::symlink_metadata(&migrations)
        .unwrap_or_else(|error| panic!("inspect migrations directory: {error}"));
    if migrations_metadata.file_type().is_symlink() {
        panic!("migrations directory must not be a symlink");
    }
    if !migrations_metadata.is_dir() {
        panic!("migrations path is not a directory");
    }
    let entries = fs::read_dir(&migrations)
        .unwrap_or_else(|error| panic!("read migrations directory: {error}"));
    for entry in entries {
        let path = entry
            .unwrap_or_else(|error| panic!("read migrations entry: {error}"))
            .path();
        let metadata = fs::symlink_metadata(&path)
            .unwrap_or_else(|error| panic!("inspect migrations entry: {error}"));
        if metadata.file_type().is_symlink() {
            panic!("migration path `{}` must not be a symlink", path.display());
        }
        if !metadata.is_dir() {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or_default();
        if !matches!(name, "sqlite" | "postgres") {
            panic!("unsupported migration dialect directory `migrations/{name}`");
        }
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}
