/** GENERATED by distributed client. Do not edit. */
import type { ReplicaOperationArtifact, ReplicaValue } from '@hops-ops/distributed/replica';

type Operation_ScalarInputs_Input_todo_bool_exp = {
  readonly "_and"?: Operation_ScalarInputs_Input_todo_bool_exp | readonly Operation_ScalarInputs_Input_todo_bool_exp[] | null;
  readonly "_or"?: Operation_ScalarInputs_Input_todo_bool_exp | readonly Operation_ScalarInputs_Input_todo_bool_exp[] | null;
  readonly "_not"?: Operation_ScalarInputs_Input_todo_bool_exp | null;
  readonly "blob"?: {
    readonly "_eq"?: string | null;
  } | null;
  readonly "completed"?: {
    readonly "_eq"?: boolean | null;
  } | null;
  readonly "id"?: {
    readonly "_eq"?: string | number | null;
  } | null;
  readonly "payload"?: {
    readonly "_eq"?: ReplicaValue | null;
  } | null;
  readonly "priority"?: {
    readonly "_eq"?: number | null;
    readonly "_in"?: number | readonly number[];
    readonly "_nin"?: number | readonly number[];
  } | null;
  readonly "sequence"?: {
    readonly "_eq"?: number | null;
    readonly "_in"?: number | readonly number[];
  } | null;
  readonly "tenantId"?: {
    readonly "_eq"?: string | number | null;
  } | null;
  readonly "title"?: {
    readonly "_eq"?: string | null;
  } | null;
  readonly "updatedAt"?: {
    readonly "_eq"?: string | null;
  } | null;
  readonly "owner"?: Operation_ScalarInputs_Input_todo_bool_exp | null;
};

type Operation_ScalarInputs_Input_todo_order_by_Direction = "asc" | "asc_nulls_first" | "asc_nulls_last" | "desc" | "desc_nulls_first" | "desc_nulls_last";
type Operation_ScalarInputs_Input_todo_order_by =
  | {
      readonly "blob": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "title"?: never;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title": Operation_ScalarInputs_Input_todo_order_by_Direction;
      readonly "updatedAt"?: never;
    }
  | {
      readonly "blob"?: never;
      readonly "completed"?: never;
      readonly "id"?: never;
      readonly "payload"?: never;
      readonly "priority"?: never;
      readonly "sequence"?: never;
      readonly "tenantId"?: never;
      readonly "title"?: never;
      readonly "updatedAt": Operation_ScalarInputs_Input_todo_order_by_Direction;
    };

export type Operation_ScalarInputs_Variables = {
  readonly "big": number;
  readonly "bytes"?: string | null;
  readonly "id": string | number;
  readonly "json"?: ReplicaValue | null;
  readonly "order"?: Operation_ScalarInputs_Input_todo_order_by | readonly Operation_ScalarInputs_Input_todo_order_by[] | null;
  readonly "timestamp"?: string | null;
  readonly "where": Operation_ScalarInputs_Input_todo_bool_exp;
};

export type Operation_ScalarInputs_Data = {
  readonly "todos": readonly {
    readonly "id": string;
  }[];
};

/** Exact canonical query bytes sent to the server. */
export const Operation_ScalarInputsDocument = "query ScalarInputs($big: BigInt!, $bytes: Bytea, $id: ID!, $json: JSON, $order: [todo_order_by!], $timestamp: Timestamptz, $where: todo_bool_exp!) {\n  todos(order_by: $order, where: {_and: [$where, {blob: {_eq: $bytes}, id: {_eq: $id}, payload: {_eq: $json}, sequence: {_eq: $big}, updatedAt: {_eq: $timestamp}}]}) {\n    id\n    _distributed_tenantId: tenantId\n    _distributed_typename: __typename\n    _distributed_blob: blob\n    _distributed_completed: completed\n    _distributed_payload: payload\n    _distributed_priority: priority\n    _distributed_sequence: sequence\n    _distributed_title: title\n    _distributed_updatedAt: updatedAt\n  }\n}\n";

/** Typed normalized-replica operation descriptor. */
export const Operation_ScalarInputs: ReplicaOperationArtifact<Operation_ScalarInputs_Data, Operation_ScalarInputs_Variables> = {
  "id": "sha256:d9f67afd74da3173c4a3b60d3dc832cc1288424a932a3784e2a8f9de3b379c13",
  "document": "query ScalarInputs($big: BigInt!, $bytes: Bytea, $id: ID!, $json: JSON, $order: [todo_order_by!], $timestamp: Timestamptz, $where: todo_bool_exp!) {\n  todos(order_by: $order, where: {_and: [$where, {blob: {_eq: $bytes}, id: {_eq: $id}, payload: {_eq: $json}, sequence: {_eq: $big}, updatedAt: {_eq: $timestamp}}]}) {\n    id\n    _distributed_tenantId: tenantId\n    _distributed_typename: __typename\n    _distributed_blob: blob\n    _distributed_completed: completed\n    _distributed_payload: payload\n    _distributed_priority: priority\n    _distributed_sequence: sequence\n    _distributed_title: title\n    _distributed_updatedAt: updatedAt\n  }\n}\n",
  "source": {
    "path": "src/routes/todos/+page.graphql",
    "line": 2,
    "column": 3
  },
  "variableCodec": {
    "version": 1,
    "limits": {
      "maxDepth": 8,
      "maxBoolWidth": 256,
      "maxInList": 1000
    },
    "variables": {
      "big": {
        "kind": "scalar",
        "scalar": "BigInt",
        "codec": "json_number_precision_limited",
        "nullable": false
      },
      "bytes": {
        "kind": "scalar",
        "scalar": "Bytea",
        "codec": "base64",
        "nullable": true
      },
      "id": {
        "kind": "scalar",
        "scalar": "ID",
        "codec": "string",
        "nullable": false
      },
      "json": {
        "kind": "scalar",
        "scalar": "JSON",
        "codec": "json",
        "nullable": true
      },
      "order": {
        "kind": "list",
        "nullable": true,
        "item": {
          "kind": "input",
          "name": "todo_order_by",
          "nullable": false
        }
      },
      "timestamp": {
        "kind": "scalar",
        "scalar": "Timestamptz",
        "codec": "string_unvalidated_timestamp",
        "nullable": true
      },
      "where": {
        "kind": "input",
        "name": "todo_bool_exp",
        "nullable": false,
        "filterBaseDepth": 1
      }
    },
    "inputs": {
      "todo_bool_exp": {
        "kind": "filter",
        "model": "Todo",
        "fields": [
          {
            "field": "blob",
            "scalar": "Bytea",
            "codec": "base64",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "completed",
            "scalar": "Boolean",
            "codec": "boolean",
            "nullable": false,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "id",
            "scalar": "ID",
            "codec": "string",
            "nullable": false,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "payload",
            "scalar": "JSON",
            "codec": "json",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "priority",
            "scalar": "Int",
            "codec": "int32",
            "nullable": false,
            "operators": [
              "_eq",
              "_in",
              "_nin"
            ]
          },
          {
            "field": "sequence",
            "scalar": "BigInt",
            "codec": "json_number_precision_limited",
            "nullable": false,
            "operators": [
              "_eq",
              "_in"
            ]
          },
          {
            "field": "tenantId",
            "scalar": "ID",
            "codec": "string",
            "nullable": false,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "title",
            "scalar": "String",
            "codec": "string",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "updatedAt",
            "scalar": "Timestamptz",
            "codec": "string_unvalidated_timestamp",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          }
        ],
        "relationships": [
          {
            "field": "owner",
            "target": {
              "kind": "input",
              "name": "todo_bool_exp"
            }
          }
        ]
      },
      "todo_order_by": {
        "kind": "order",
        "model": "Todo",
        "fields": [
          {
            "field": "blob",
            "scalar": "Bytea",
            "codec": "base64",
            "nullable": true
          },
          {
            "field": "completed",
            "scalar": "Boolean",
            "codec": "boolean",
            "nullable": false
          },
          {
            "field": "id",
            "scalar": "ID",
            "codec": "string",
            "nullable": false
          },
          {
            "field": "payload",
            "scalar": "JSON",
            "codec": "json",
            "nullable": true
          },
          {
            "field": "priority",
            "scalar": "Int",
            "codec": "int32",
            "nullable": false
          },
          {
            "field": "sequence",
            "scalar": "BigInt",
            "codec": "json_number_precision_limited",
            "nullable": false
          },
          {
            "field": "tenantId",
            "scalar": "ID",
            "codec": "string",
            "nullable": false
          },
          {
            "field": "title",
            "scalar": "String",
            "codec": "string",
            "nullable": true
          },
          {
            "field": "updatedAt",
            "scalar": "Timestamptz",
            "codec": "string_unvalidated_timestamp",
            "nullable": true
          }
        ],
        "values": [
          "asc",
          "asc_nulls_first",
          "asc_nulls_last",
          "desc",
          "desc_nulls_first",
          "desc_nulls_last"
        ]
      }
    }
  },
  "roots": [
    {
      "responseKey": "todos",
      "field": "todos",
      "cardinality": "many",
      "nullable": false,
      "arguments": {
        "order_by": {
          "kind": "variable",
          "name": "order"
        },
        "where": {
          "kind": "object",
          "fields": {
            "_and": {
              "kind": "list",
              "items": [
                {
                  "kind": "variable",
                  "name": "where"
                },
                {
                  "kind": "object",
                  "fields": {
                    "blob": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "bytes"
                        }
                      }
                    },
                    "id": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "id"
                        }
                      }
                    },
                    "payload": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "json"
                        }
                      }
                    },
                    "sequence": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "big"
                        }
                      }
                    },
                    "updatedAt": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "timestamp"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "dependencies": [
        "todo_rows"
      ],
      "coverage": {
        "kind": "offset",
        "offsetArgument": "offset",
        "limitArgument": "limit",
        "defaultLimit": 25,
        "maxLimit": 100
      },
      "filter": {
        "input": {
          "kind": "object",
          "fields": {
            "_and": {
              "kind": "list",
              "items": [
                {
                  "kind": "variable",
                  "name": "where"
                },
                {
                  "kind": "object",
                  "fields": {
                    "blob": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "bytes"
                        }
                      }
                    },
                    "id": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "id"
                        }
                      }
                    },
                    "payload": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "json"
                        }
                      }
                    },
                    "sequence": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "big"
                        }
                      }
                    },
                    "updatedAt": {
                      "kind": "object",
                      "fields": {
                        "_eq": {
                          "kind": "variable",
                          "name": "timestamp"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        "fields": [
          {
            "field": "blob",
            "scalar": "Bytea",
            "codec": "base64",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "completed",
            "scalar": "Boolean",
            "codec": "boolean",
            "nullable": false,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "id",
            "scalar": "ID",
            "codec": "string",
            "nullable": false,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "payload",
            "scalar": "JSON",
            "codec": "json",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "priority",
            "scalar": "Int",
            "codec": "int32",
            "nullable": false,
            "operators": [
              "_eq",
              "_in",
              "_nin"
            ]
          },
          {
            "field": "sequence",
            "scalar": "BigInt",
            "codec": "json_number_precision_limited",
            "nullable": false,
            "operators": [
              "_eq",
              "_in"
            ]
          },
          {
            "field": "tenantId",
            "scalar": "ID",
            "codec": "string",
            "nullable": false,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "title",
            "scalar": "String",
            "codec": "string",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          },
          {
            "field": "updatedAt",
            "scalar": "Timestamptz",
            "codec": "string_unvalidated_timestamp",
            "nullable": true,
            "operators": [
              "_eq"
            ]
          }
        ],
        "relationships": [
          {
            "field": "owner",
            "targetModel": "Todo",
            "kind": "belongs_to",
            "keyMapping": {
              "kind": "embedded"
            },
            "maintenance": "revalidate",
            "dependencies": [
              "todo_rows"
            ]
          }
        ],
        "rowPolicy": {
          "kind": "unrestricted"
        }
      },
      "order": {
        "input": {
          "kind": "variable",
          "name": "order"
        },
        "fields": [
          {
            "field": "blob",
            "scalar": "Bytea",
            "codec": "base64",
            "nullable": true
          },
          {
            "field": "completed",
            "scalar": "Boolean",
            "codec": "boolean",
            "nullable": false
          },
          {
            "field": "id",
            "scalar": "ID",
            "codec": "string",
            "nullable": false
          },
          {
            "field": "payload",
            "scalar": "JSON",
            "codec": "json",
            "nullable": true
          },
          {
            "field": "priority",
            "scalar": "Int",
            "codec": "int32",
            "nullable": false
          },
          {
            "field": "sequence",
            "scalar": "BigInt",
            "codec": "json_number_precision_limited",
            "nullable": false
          },
          {
            "field": "tenantId",
            "scalar": "ID",
            "codec": "string",
            "nullable": false
          },
          {
            "field": "title",
            "scalar": "String",
            "codec": "string",
            "nullable": true
          },
          {
            "field": "updatedAt",
            "scalar": "Timestamptz",
            "codec": "string_unvalidated_timestamp",
            "nullable": true
          }
        ],
        "tieBreakers": [
          {
            "field": "tenantId",
            "scalar": "ID",
            "codec": "string",
            "nullable": false
          },
          {
            "field": "id",
            "scalar": "ID",
            "codec": "string",
            "nullable": false
          }
        ]
      },
      "pagination": {
        "kind": "offset",
        "insert": "local",
        "delete": "local",
        "reorder": "local",
        "stableUpdate": "local"
      },
      "selection": {
        "typename": "todo",
        "storage": {
          "kind": "normalized",
          "model": "Todo",
          "identityFields": [
            "tenantId",
            "id"
          ]
        },
        "members": [
          {
            "kind": "scalar",
            "responseKey": "id",
            "field": "id",
            "codec": "string",
            "nullable": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_tenantId",
            "field": "tenantId",
            "codec": "string",
            "nullable": false,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_typename",
            "field": "__typename",
            "codec": "string",
            "nullable": false,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_blob",
            "field": "blob",
            "codec": "base64",
            "nullable": true,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_completed",
            "field": "completed",
            "codec": "boolean",
            "nullable": false,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_payload",
            "field": "payload",
            "codec": "json",
            "nullable": true,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_priority",
            "field": "priority",
            "codec": "int32",
            "nullable": false,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_sequence",
            "field": "sequence",
            "codec": "json_number_precision_limited",
            "nullable": false,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_title",
            "field": "title",
            "codec": "string",
            "nullable": true,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_updatedAt",
            "field": "updatedAt",
            "codec": "string_unvalidated_timestamp",
            "nullable": true,
            "expose": false
          }
        ]
      }
    }
  ],
  "protocol": {
    "version": 1,
    "schemaHash": "sha256:1b203cdad2827a6b52ac96e6d4d9114e160312cf93196a3d489dde2d5e331526",
    "surface": {
      "kind": "role",
      "name": "user"
    },
    "operation": "sha256:d9f67afd74da3173c4a3b60d3dc832cc1288424a932a3784e2a8f9de3b379c13",
    "trustedPresets": []
  }
};
