/** GENERATED by dctl client. Do not edit. */

import {
  createReplicaCommandRuntime,
  prepareReplicaCommand
} from '@hops-ops/distributed/replica';

import type {
  DistributedReplica,
  PrepareReplicaCommandOptions,
  ReplicaCommandArtifact,
  ReplicaCommandRuntime,
  ReplicaCommandRuntimeOptions,
  ReplicaCommandTransport,
  ReplicaPreparedCommand,
  ReplicaValue
} from '@hops-ops/distributed/replica';

import { COMMAND_STATUS } from './protocol.js';

export type Command_importTodos_Input = {
  readonly "source": ReplicaValue;
};

export type Command_importTodos_Output = {
  readonly "result": ReplicaValue;
};

/** Exact typed causal command descriptor and full mutation bytes. */
export const Command_importTodos: ReplicaCommandArtifact<Command_importTodos_Input, Command_importTodos_Output> = {
  "consistency": "accepted",
  "document": "mutation Client_importTodos($commandId: ID!, $input: ImportTodosInput!) { importTodos(commandId: $commandId, input: $input) { result } }",
  "effects": {
    "fallback": "revalidate",
    "operations": [],
    "version": 1
  },
  "input": {
    "definition": {
      "fields": [
        {
          "codec": "json",
          "itemNullable": false,
          "list": false,
          "name": "source",
          "nullable": false,
          "typeName": "JSON"
        }
      ],
      "name": "ImportTodosInput"
    },
    "kind": "object"
  },
  "mutationField": "importTodos",
  "name": "todo.import",
  "operationHash": "sha256:e8e54238fd7618fa94e90ae60b1dfac8833943027d04e71be84cb03702f1cebf",
  "output": {
    "definition": {
      "fields": [
        {
          "codec": "json",
          "itemNullable": false,
          "list": false,
          "name": "result",
          "nullable": false,
          "typeName": "JSON"
        }
      ],
      "name": "ImportTodosPayload"
    },
    "kind": "object"
  },
  "protocol": {
    "operation": "sha256:e8e54238fd7618fa94e90ae60b1dfac8833943027d04e71be84cb03702f1cebf",
    "protocolHash": "sha256:7631d15b16e327ff08d728e97ac5f90f5150d00774938e720bbbc6830b77e0cf",
    "schemaHash": "sha256:6e5b0d5fee51d8bb8ce7cf286bd8ecf06d6dcdbc2a59b4c9fb24d24d8ae7a541",
    "surface": {
      "kind": "role",
      "name": "user"
    },
    "trustedPresets": [],
    "version": 2
  },
  "revalidation": {
    "dependencies": [
      "todo_rows"
    ],
    "models": [
      "Todo"
    ],
    "relationships": [],
    "required": true,
    "version": 1
  },
  "version": 1
};

export function prepareCommand_importTodos(
  input: Command_importTodos_Input,
  options?: PrepareReplicaCommandOptions
): ReplicaPreparedCommand<Command_importTodos_Input, Command_importTodos_Output> {
  return prepareReplicaCommand(Command_importTodos, input, options);
}

export type Command_pingTodos_Input = void;

export type Command_pingTodos_Output = {
  readonly "ok": boolean;
};

/** Exact typed causal command descriptor and full mutation bytes. */
export const Command_pingTodos: ReplicaCommandArtifact<Command_pingTodos_Input, Command_pingTodos_Output> = {
  "consistency": "accepted",
  "document": "mutation Client_pingTodos($commandId: ID!) { pingTodos(commandId: $commandId) { ok } }",
  "effects": {
    "fallback": "revalidate",
    "operations": [],
    "version": 1
  },
  "input": {
    "kind": "none"
  },
  "mutationField": "pingTodos",
  "name": "todo.ping",
  "operationHash": "sha256:3cb3c1e96331b4e98191cc725ab6b01c0e9b04cc7cc0f37f4fa0ef394fee9acf",
  "output": {
    "definition": {
      "fields": [
        {
          "codec": "boolean",
          "itemNullable": false,
          "list": false,
          "name": "ok",
          "nullable": false,
          "typeName": "Boolean"
        }
      ],
      "name": "PingTodosPayload"
    },
    "kind": "object"
  },
  "protocol": {
    "operation": "sha256:3cb3c1e96331b4e98191cc725ab6b01c0e9b04cc7cc0f37f4fa0ef394fee9acf",
    "protocolHash": "sha256:7631d15b16e327ff08d728e97ac5f90f5150d00774938e720bbbc6830b77e0cf",
    "schemaHash": "sha256:6e5b0d5fee51d8bb8ce7cf286bd8ecf06d6dcdbc2a59b4c9fb24d24d8ae7a541",
    "surface": {
      "kind": "role",
      "name": "user"
    },
    "trustedPresets": [],
    "version": 2
  },
  "revalidation": {
    "dependencies": [
      "todo_rows"
    ],
    "models": [
      "Todo"
    ],
    "relationships": [],
    "required": true,
    "version": 1
  },
  "version": 1
};

export function prepareCommand_pingTodos(
  options?: PrepareReplicaCommandOptions
): ReplicaPreparedCommand<Command_pingTodos_Input, Command_pingTodos_Output> {
  return prepareReplicaCommand(Command_pingTodos, undefined, options);
}

export type Command_projectTodo_Input = {
  readonly "id": string;
  readonly "tenantId": string;
};

export type Command_projectTodo_Output = {
  readonly "completed": boolean;
  readonly "id": string;
  readonly "priority": number;
  readonly "tenantId": string;
  readonly "title": string | null;
};

/** Exact typed causal command descriptor and full mutation bytes. */
export const Command_projectTodo: ReplicaCommandArtifact<Command_projectTodo_Input, Command_projectTodo_Output> = {
  "consistency": "projected",
  "directProjection": {
    "changeEpoch": "todos-v1",
    "identityFields": [
      "tenantId",
      "id"
    ],
    "model": "Todo",
    "partition": {
      "kind": "input",
      "path": [
        "tenantId"
      ]
    },
    "topology": {
      "digest": "sha256:b44a23c0c3e5bb3c7f72da0ec21789206f8880508d9cd60145a9a0793113490e",
      "name": "todos",
      "version": 1
    }
  },
  "document": "mutation Client_projectTodo($commandId: ID!, $input: ProjectTodoInput!) { projectTodo(commandId: $commandId, input: $input) { completed id priority tenantId title } }",
  "effects": {
    "fallback": "revalidate",
    "operations": [],
    "version": 1
  },
  "input": {
    "definition": {
      "fields": [
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "id",
          "nullable": false,
          "typeName": "ID"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "tenantId",
          "nullable": false,
          "typeName": "ID"
        }
      ],
      "name": "ProjectTodoInput"
    },
    "kind": "object"
  },
  "mutationField": "projectTodo",
  "name": "todo.project",
  "operationHash": "sha256:f986d060555cdedfe94621914116306af704d8bb90e75289722a3b7119211d32",
  "output": {
    "definition": {
      "fields": [
        {
          "codec": "boolean",
          "itemNullable": false,
          "list": false,
          "name": "completed",
          "nullable": false,
          "typeName": "Boolean"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "id",
          "nullable": false,
          "typeName": "ID"
        },
        {
          "codec": "int32",
          "itemNullable": false,
          "list": false,
          "name": "priority",
          "nullable": false,
          "typeName": "Int"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "tenantId",
          "nullable": false,
          "typeName": "ID"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "title",
          "nullable": true,
          "typeName": "String"
        }
      ],
      "name": "todo"
    },
    "kind": "object"
  },
  "protocol": {
    "operation": "sha256:f986d060555cdedfe94621914116306af704d8bb90e75289722a3b7119211d32",
    "protocolHash": "sha256:7631d15b16e327ff08d728e97ac5f90f5150d00774938e720bbbc6830b77e0cf",
    "schemaHash": "sha256:6e5b0d5fee51d8bb8ce7cf286bd8ecf06d6dcdbc2a59b4c9fb24d24d8ae7a541",
    "surface": {
      "kind": "role",
      "name": "user"
    },
    "trustedPresets": [],
    "version": 2
  },
  "revalidation": {
    "dependencies": [
      "todo_rows"
    ],
    "models": [
      "Todo"
    ],
    "relationships": [],
    "required": true,
    "version": 1
  },
  "version": 1
};

export function prepareCommand_projectTodo(
  input: Command_projectTodo_Input,
  options?: PrepareReplicaCommandOptions
): ReplicaPreparedCommand<Command_projectTodo_Input, Command_projectTodo_Output> {
  return prepareReplicaCommand(Command_projectTodo, input, options);
}

export const COMMAND_ARTIFACTS = [Command_importTodos, Command_pingTodos, Command_projectTodo] as const;

/** Inspectable command inventory consumed by the generated binding factory. */
export const COMMANDS = {
  "todo.import": Command_importTodos,
  "todo.ping": Command_pingTodos,
  "todo.project": Command_projectTodo
} as const;

/** Runtime owning the generated callable command surface and its causal lifecycle. */
export type GeneratedCommandRuntime = ReplicaCommandRuntime<typeof COMMANDS>;

/** Callable `commands.x(input)` surface exposed by GeneratedCommandRuntime. */
export type GeneratedCommands = GeneratedCommandRuntime['commands'];

/** Runtime options excluding compiler-owned protocol authority. */
export type GeneratedCommandRuntimeOptions = Omit<ReplicaCommandRuntimeOptions, 'status'>;

/**
 * Bind this generated command inventory to a replica and transport.
 * Keep the returned runtime when `observeResult` or `dispose` is needed.
 */
export function createCommands(
  replica: DistributedReplica,
  transport: ReplicaCommandTransport,
  options?: GeneratedCommandRuntimeOptions
): GeneratedCommandRuntime {
  return createReplicaCommandRuntime(replica, transport, COMMANDS, {
    ...options,
    status: COMMAND_STATUS
  });
}

/** Projector topology used by command confirmation/effect runtimes. */
export const PROJECTOR_ARTIFACTS = [
  {
    "version": 1,
    "name": "todos",
    "facts": [
      "TodoProjected"
    ],
    "models": [
      "Todo"
    ],
    "dependencies": [
      "todo_rows"
    ],
    "causal_confirmation": false
  }
] as const;

export type GeneratedCommandArtifact = (typeof COMMAND_ARTIFACTS)[number];
