/** GENERATED by dctl client. Do not edit. */

import { prepareReplicaCommand } from '@hops-ops/distributed/replica';

import type {
  PrepareReplicaCommandOptions,
  ReplicaCommandArtifact,
  ReplicaPreparedCommand,
  ReplicaValue
} from '@hops-ops/distributed/replica';

export type Command_importTodos_Input = ReplicaValue;

export type Command_importTodos_Output = ReplicaValue;

/** Exact typed causal command descriptor and full mutation bytes. */
export const Command_importTodos: ReplicaCommandArtifact<Command_importTodos_Input, Command_importTodos_Output> = {
  "consistency": "accepted",
  "document": "mutation Client_importTodos($commandId: ID!, $input: JSON!) { importTodos(commandId: $commandId, input: $input) }",
  "effects": {
    "fallback": "revalidate",
    "operations": [],
    "version": 1
  },
  "input": {
    "codec": "json",
    "kind": "json"
  },
  "mutationField": "importTodos",
  "name": "todo.import",
  "operationHash": "sha256:4de86b23830266823fab843da7dfc060b17dd3ef1991f67616b5af7d5d94bf12",
  "output": {
    "codec": "json",
    "kind": "json"
  },
  "protocol": {
    "operation": "sha256:4de86b23830266823fab843da7dfc060b17dd3ef1991f67616b5af7d5d94bf12",
    "protocolHash": "sha256:50a3690689ff5aa7cefc88bb7b5d6f1e1a64615e7644d306403287c09b1e59dc",
    "schemaHash": "sha256:9628515198bbad604f45b47b225dabc420fc55779daeaa3562c2712bb168c0ec",
    "version": 2
  },
  "revalidation": {
    "dependencies": [
      "todo_rows"
    ],
    "models": [
      "Todo"
    ],
    "relationships": [],
    "required": true,
    "version": 1
  },
  "version": 1
};

export function prepareCommand_importTodos(
  input: Command_importTodos_Input,
  options?: PrepareReplicaCommandOptions
): ReplicaPreparedCommand<Command_importTodos_Input, Command_importTodos_Output> {
  return prepareReplicaCommand(Command_importTodos, input, options);
}

export type Command_pingTodos_Input = void;

export type Command_pingTodos_Output = ReplicaValue;

/** Exact typed causal command descriptor and full mutation bytes. */
export const Command_pingTodos: ReplicaCommandArtifact<Command_pingTodos_Input, Command_pingTodos_Output> = {
  "consistency": "accepted",
  "document": "mutation Client_pingTodos($commandId: ID!) { pingTodos(commandId: $commandId) }",
  "effects": {
    "fallback": "revalidate",
    "operations": [],
    "version": 1
  },
  "input": {
    "kind": "none"
  },
  "mutationField": "pingTodos",
  "name": "todo.ping",
  "operationHash": "sha256:c2e57712f08ce1b185b07393c2f6ee30e40a4e50608509497dcd303e5ff3c100",
  "output": {
    "codec": "json",
    "kind": "json"
  },
  "protocol": {
    "operation": "sha256:c2e57712f08ce1b185b07393c2f6ee30e40a4e50608509497dcd303e5ff3c100",
    "protocolHash": "sha256:50a3690689ff5aa7cefc88bb7b5d6f1e1a64615e7644d306403287c09b1e59dc",
    "schemaHash": "sha256:9628515198bbad604f45b47b225dabc420fc55779daeaa3562c2712bb168c0ec",
    "version": 2
  },
  "revalidation": {
    "dependencies": [
      "todo_rows"
    ],
    "models": [
      "Todo"
    ],
    "relationships": [],
    "required": true,
    "version": 1
  },
  "version": 1
};

export function prepareCommand_pingTodos(
  options?: PrepareReplicaCommandOptions
): ReplicaPreparedCommand<Command_pingTodos_Input, Command_pingTodos_Output> {
  return prepareReplicaCommand(Command_pingTodos, undefined, options);
}

export type Command_projectTodo_Input = {
  readonly "id": string;
  readonly "tenantId": string;
};

export type Command_projectTodo_Output = {
  readonly "completed": boolean;
  readonly "id": string;
  readonly "priority": number;
  readonly "tenantId": string;
  readonly "title": string | null;
};

/** Exact typed causal command descriptor and full mutation bytes. */
export const Command_projectTodo: ReplicaCommandArtifact<Command_projectTodo_Input, Command_projectTodo_Output> = {
  "consistency": "projected",
  "directProjection": {
    "changeEpoch": "todos-v1",
    "identityFields": [
      "tenantId",
      "id"
    ],
    "model": "Todo",
    "partition": {
      "kind": "input",
      "path": [
        "tenantId"
      ]
    },
    "topology": {
      "digest": "sha256:b44a23c0c3e5bb3c7f72da0ec21789206f8880508d9cd60145a9a0793113490e",
      "name": "todos",
      "version": 1
    }
  },
  "document": "mutation Client_projectTodo($commandId: ID!, $input: ProjectTodoInput!) { projectTodo(commandId: $commandId, input: $input) { completed id priority tenantId title } }",
  "effects": {
    "fallback": "revalidate",
    "operations": [],
    "version": 1
  },
  "input": {
    "definition": {
      "fields": [
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "id",
          "nullable": false,
          "typeName": "ID"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "tenantId",
          "nullable": false,
          "typeName": "ID"
        }
      ],
      "name": "ProjectTodoInput"
    },
    "kind": "object"
  },
  "mutationField": "projectTodo",
  "name": "todo.project",
  "operationHash": "sha256:f986d060555cdedfe94621914116306af704d8bb90e75289722a3b7119211d32",
  "output": {
    "definition": {
      "fields": [
        {
          "codec": "boolean",
          "itemNullable": false,
          "list": false,
          "name": "completed",
          "nullable": false,
          "typeName": "Boolean"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "id",
          "nullable": false,
          "typeName": "ID"
        },
        {
          "codec": "int32",
          "itemNullable": false,
          "list": false,
          "name": "priority",
          "nullable": false,
          "typeName": "Int"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "tenantId",
          "nullable": false,
          "typeName": "ID"
        },
        {
          "codec": "string",
          "itemNullable": false,
          "list": false,
          "name": "title",
          "nullable": true,
          "typeName": "String"
        }
      ],
      "name": "todo"
    },
    "kind": "object"
  },
  "protocol": {
    "operation": "sha256:f986d060555cdedfe94621914116306af704d8bb90e75289722a3b7119211d32",
    "protocolHash": "sha256:50a3690689ff5aa7cefc88bb7b5d6f1e1a64615e7644d306403287c09b1e59dc",
    "schemaHash": "sha256:9628515198bbad604f45b47b225dabc420fc55779daeaa3562c2712bb168c0ec",
    "version": 2
  },
  "revalidation": {
    "dependencies": [
      "todo_rows"
    ],
    "models": [
      "Todo"
    ],
    "relationships": [],
    "required": true,
    "version": 1
  },
  "version": 1
};

export function prepareCommand_projectTodo(
  input: Command_projectTodo_Input,
  options?: PrepareReplicaCommandOptions
): ReplicaPreparedCommand<Command_projectTodo_Input, Command_projectTodo_Output> {
  return prepareReplicaCommand(Command_projectTodo, input, options);
}

export const COMMAND_ARTIFACTS = [Command_importTodos, Command_pingTodos, Command_projectTodo] as const;

/** Typed framework-neutral command entrypoints. */
export const commands = {
  "todo.import": { artifact: Command_importTodos, prepare: prepareCommand_importTodos },
  "todo.ping": { artifact: Command_pingTodos, prepare: prepareCommand_pingTodos },
  "todo.project": { artifact: Command_projectTodo, prepare: prepareCommand_projectTodo }
} as const;

/** Projector topology used by command confirmation/effect runtimes. */
export const PROJECTOR_ARTIFACTS = [
  {
    "version": 1,
    "name": "todos",
    "facts": [
      "TodoProjected"
    ],
    "models": [
      "Todo"
    ],
    "dependencies": [
      "todo_rows"
    ],
    "causal_confirmation": false
  }
] as const;

export type GeneratedCommandArtifact = (typeof COMMAND_ARTIFACTS)[number];
