/** GENERATED by dctl client. Do not edit. */
import type { ReplicaOperationArtifact } from '@hops-ops/distributed/replica';

export type Operation_RustRuntimeBridge_Variables = {
  readonly "id": string | number;
  readonly "tenantId": string | number;
};

export type Operation_RustRuntimeBridge_Data = {
  readonly "todo": {
    readonly "id": string;
    readonly "title": string | null;
  } | null;
};

/** Exact canonical query bytes sent to the server. */
export const Operation_RustRuntimeBridgeDocument = "query RustRuntimeBridge($id: ID!, $tenantId: ID!) {\n  todo(id: $id, tenantId: $tenantId) {\n    id\n    title\n    _distributed_tenantId: tenantId\n    _distributed_typename: __typename\n  }\n}\n";

/** Typed normalized-replica operation descriptor. */
export const Operation_RustRuntimeBridge: ReplicaOperationArtifact<Operation_RustRuntimeBridge_Data, Operation_RustRuntimeBridge_Variables> = {
  "id": "sha256:8cd0dd25a9328638e46aa285dc34bbc36be7738616a81bfa26e973ad41ab2878",
  "document": "query RustRuntimeBridge($id: ID!, $tenantId: ID!) {\n  todo(id: $id, tenantId: $tenantId) {\n    id\n    title\n    _distributed_tenantId: tenantId\n    _distributed_typename: __typename\n  }\n}\n",
  "variableCodec": {
    "version": 2,
    "limits": {
      "maxDepth": 8,
      "maxBoolWidth": 256,
      "maxInList": 1000
    },
    "variables": {
      "id": {
        "kind": "scalar",
        "scalar": "ID",
        "codec": "string",
        "nullable": false
      },
      "tenantId": {
        "kind": "scalar",
        "scalar": "ID",
        "codec": "string",
        "nullable": false
      }
    },
    "inputs": {}
  },
  "roots": [
    {
      "responseKey": "todo",
      "field": "todo",
      "cardinality": "one",
      "nullable": true,
      "arguments": {
        "id": {
          "kind": "variable",
          "name": "id"
        },
        "tenantId": {
          "kind": "variable",
          "name": "tenantId"
        }
      },
      "dependencies": [
        "todo_rows"
      ],
      "coverage": {
        "kind": "complete"
      },
      "selection": {
        "typename": "todo",
        "storage": {
          "kind": "normalized",
          "model": "Todo",
          "identityFields": [
            "tenantId",
            "id"
          ]
        },
        "members": [
          {
            "kind": "scalar",
            "responseKey": "id",
            "field": "id",
            "codec": "string",
            "nullable": false
          },
          {
            "kind": "scalar",
            "responseKey": "title",
            "field": "title",
            "codec": "string",
            "nullable": true
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_tenantId",
            "field": "tenantId",
            "codec": "string",
            "nullable": false,
            "expose": false
          },
          {
            "kind": "scalar",
            "responseKey": "_distributed_typename",
            "field": "__typename",
            "codec": "string",
            "nullable": false,
            "expose": false
          }
        ]
      }
    }
  ],
  "protocol": {
    "version": 2,
    "schemaHash": "sha256:932aaf585be36d8eb05c646a66a1c44c94303f398577c71512491d26347e78f5",
    "surface": {
      "kind": "role",
      "name": "user"
    },
    "operation": "sha256:8cd0dd25a9328638e46aa285dc34bbc36be7738616a81bfa26e973ad41ab2878"
  }
};
