/** GENERATED by distributed client. Do not edit. */

import { createLazyReplicaCommandRuntime } from '@hops-ops/distributed/replica/lazy';
import type { DistributedReplica, ReplicaCommandTransport, ReplicaLazyCommandRuntime } from '@hops-ops/distributed/replica';
import type { COMMANDS, GeneratedCommandRuntimeOptions } from './generated-commands.js';
import { COMMAND_STATUS } from './protocol.js';

const COMMAND_CATALOG = {
  "todo.import": {
    "hasInput": true,
    "operationHash": "sha256:e8e54238fd7618fa94e90ae60b1dfac8833943027d04e71be84cb03702f1cebf"
  },
  "todo.ping": {
    "hasInput": false,
    "operationHash": "sha256:3cb3c1e96331b4e98191cc725ab6b01c0e9b04cc7cc0f37f4fa0ef394fee9acf"
  },
  "todo.project": {
    "hasInput": true,
    "operationHash": "sha256:f986d060555cdedfe94621914116306af704d8bb90e75289722a3b7119211d32"
  }
} as const;

/** Register authority now; import one shared runtime on preload or first command. */
export function createLazyCommands(
  replica: DistributedReplica,
  transport: ReplicaCommandTransport,
  options?: GeneratedCommandRuntimeOptions
): ReplicaLazyCommandRuntime<typeof COMMANDS> {
  return createLazyReplicaCommandRuntime<typeof COMMANDS>(replica, transport,
    { commands: COMMAND_CATALOG, status: COMMAND_STATUS },
    () => import('./generated-commands.js').then(({ COMMANDS }) => ({ entries: COMMANDS })), options);
}
