[package]
name = "e2e-service"
version.workspace = true
edition.workspace = true
publish = false
description = "Todo service library: commands, projectors, GraphQL"

[dependencies]
distributed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
axum = { workspace = true }
tower = "0.5"
futures-util = "0.3"
todo-domain = { path = "../todo-domain" }
chat-domain = { path = "../chat-domain" }
e2e-readmodels = { path = "../readmodels" }
