[package]
name = "application-contract-only"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[features]
default = []
application-runtime = ["distributed/application-runtime"]
linked-unlisted = ["dep:application-unlisted"]

[dependencies]
distributed = { path = "../../..", default-features = false }
application-unlisted = { path = "../application-unlisted", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
