/**
 * GENERATED by @hops-ops/distributed — do not edit by hand.
 * Source: commands.manifest.json client_reconcile hints
 * Regenerate with: distributed-gen-commands
 */
import type { CommandPolicyMap } from '@hops-ops/distributed';
import type { COMMANDS } from "./commands.generated.js";

/** Call-site options override these generated defaults. */
export const commandPolicies = {
  todosCreate: {
    result: { kind: "fact" },
    reconcile: { kind: "none" },
  },
  todosComplete: {
    result: { kind: "fact" },
    reconcile: { kind: "none" },
  },
  todosArchive: {
    result: { kind: "fact" },
    reconcile: { kind: "none" },
  },
  todosForceArchive: {
    result: { kind: "fact" },
    reconcile: { kind: "none" },
  },
  todosRename: {
    result: { kind: "fact" },
    reconcile: { kind: "none" },
  },
  todosReopen: {
    result: { kind: "fact" },
    reconcile: { kind: "none" },
  },
  chatMessagesPost: {
    result: { kind: "fact" },
    reconcile: { kind: "subscription" },
  },
  blobGamesStart: {
    result: { kind: "projection" },
    reconcile: { kind: "none" },
  },
  blobGamesMove: {
    result: { kind: "projection" },
    reconcile: { kind: "none" },
  },
  blobGamesStartLevel: {
    result: { kind: "projection" },
    reconcile: { kind: "none" },
  },
} satisfies CommandPolicyMap<typeof COMMANDS>;
