/**
 * GENERATED by @hops-ops/distributed — do not edit by hand.
 * Source: commands.manifest.json
 * Regenerate with: distributed-gen-commands
 */
import {
  bindCommands as bindDistributedCommands,
  defineCommand,
  defineCommands,
  executeCommand,
  type BindCommandsOptions,
  type BoundCommandSet,
  type CommandClient,
  type GqlResult
} from '@hops-ops/distributed';

export type TodoCreateInput = {
  todo_id: string;
  title: string;
};

export type TodoCreatePayload = {
  todo_id: string;
  owner_id: string;
  title: string;
  status: string;
};

export type TodoCompleteInput = {
  todo_id: string;
};

export type TodoStatusPayload = {
  todo_id: string;
  status: string;
};

export type TodoArchiveInput = {
  todo_id: string;
};

export type TodoForceArchiveInput = {
  todo_id: string;
};

export type TodoForceArchivePayload = {
  todo_id: string;
  owner_id: string;
  status: string;
  archived_by: string;
};

export type TodoRenameInput = {
  todo_id: string;
  title: string;
};

export type TodoRenamePayload = {
  todo_id: string;
  title: string;
  status: string;
};

export type TodoReopenInput = {
  todo_id: string;
};

export type ChatPostInput = {
  message_id: string;
  body: string;
  room_id?: string | null;
};

export type ChatPostPayload = {
  message_id: string;
  room_id: string;
  author_id: string;
  body: string;
  created_at: string;
};

export type BlobStartInput = {
  game_id: string;
};

export type BlobGamePayload = {
  game_id: string;
  owner_id: string;
  score: number;
  player_dead: boolean;
  current_level: number;
  current_level_completed: boolean;
  map_json: string;
  status: string;
};

export type BlobMoveInput = {
  game_id: string;
  direction: string;
};

export type BlobStartLevelInput = {
  game_id: string;
};

/** Field name to engine roles. Client metadata is not an authorization boundary. */
export const COMMAND_ROLES = {
  "todos_create": ["user", "admin"] as const,
  "todos_complete": ["user", "admin"] as const,
  "todos_archive": ["user", "admin"] as const,
  "todos_force_archive": ["admin"] as const,
  "todos_rename": ["user", "admin"] as const,
  "todos_reopen": ["user", "admin"] as const,
  "chat_messages_post": ["user", "admin"] as const,
  "blob_games_start": ["user", "admin"] as const,
  "blob_games_move": ["user", "admin"] as const,
  "blob_games_start_level": ["user", "admin"] as const,
} as const;

/** Mutation documents mirrored in commands.operations.gql. */
export const COMMAND_DOCS = {
  "todos_create": `
mutation Command_todos_create($input: TodoCreateInput!) {
  todos_create(input: $input) {
    todo_id
    owner_id
    title
    status
  }
}
`,
  "todos_complete": `
mutation Command_todos_complete($input: TodoCompleteInput!) {
  todos_complete(input: $input) {
    todo_id
    status
  }
}
`,
  "todos_archive": `
mutation Command_todos_archive($input: TodoArchiveInput!) {
  todos_archive(input: $input) {
    todo_id
    status
  }
}
`,
  "todos_force_archive": `
mutation Command_todos_force_archive($input: TodoForceArchiveInput!) {
  todos_force_archive(input: $input) {
    todo_id
    owner_id
    status
    archived_by
  }
}
`,
  "todos_rename": `
mutation Command_todos_rename($input: TodoRenameInput!) {
  todos_rename(input: $input) {
    todo_id
    title
    status
  }
}
`,
  "todos_reopen": `
mutation Command_todos_reopen($input: TodoReopenInput!) {
  todos_reopen(input: $input) {
    todo_id
    status
  }
}
`,
  "chat_messages_post": `
mutation Command_chat_messages_post($input: ChatPostInput!) {
  chat_messages_post(input: $input) {
    message_id
    room_id
    author_id
    body
    created_at
  }
}
`,
  "blob_games_start": `
mutation Command_blob_games_start($input: BlobStartInput!) {
  blob_games_start(input: $input) {
    game_id
    owner_id
    score
    player_dead
    current_level
    current_level_completed
    map_json
    status
  }
}
`,
  "blob_games_move": `
mutation Command_blob_games_move($input: BlobMoveInput!) {
  blob_games_move(input: $input) {
    game_id
    owner_id
    score
    player_dead
    current_level
    current_level_completed
    map_json
    status
  }
}
`,
  "blob_games_start_level": `
mutation Command_blob_games_start_level($input: BlobStartLevelInput!) {
  blob_games_start_level(input: $input) {
    game_id
    owner_id
    score
    player_dead
    current_level
    current_level_completed
    map_json
    status
  }
}
`,
} as const;

/** Typed command descriptors consumed by the package runtime. */
export const COMMANDS = defineCommands({
  todosCreate: defineCommand<TodoCreateInput, TodoCreatePayload>({
    field: "todos_create",
    document: COMMAND_DOCS["todos_create"],
    hasInput: true,
    roles: COMMAND_ROLES["todos_create"]
  }),
  todosComplete: defineCommand<TodoCompleteInput, TodoStatusPayload>({
    field: "todos_complete",
    document: COMMAND_DOCS["todos_complete"],
    hasInput: true,
    roles: COMMAND_ROLES["todos_complete"]
  }),
  todosArchive: defineCommand<TodoArchiveInput, TodoStatusPayload>({
    field: "todos_archive",
    document: COMMAND_DOCS["todos_archive"],
    hasInput: true,
    roles: COMMAND_ROLES["todos_archive"]
  }),
  todosForceArchive: defineCommand<TodoForceArchiveInput, TodoForceArchivePayload>({
    field: "todos_force_archive",
    document: COMMAND_DOCS["todos_force_archive"],
    hasInput: true,
    roles: COMMAND_ROLES["todos_force_archive"]
  }),
  todosRename: defineCommand<TodoRenameInput, TodoRenamePayload>({
    field: "todos_rename",
    document: COMMAND_DOCS["todos_rename"],
    hasInput: true,
    roles: COMMAND_ROLES["todos_rename"]
  }),
  todosReopen: defineCommand<TodoReopenInput, TodoStatusPayload>({
    field: "todos_reopen",
    document: COMMAND_DOCS["todos_reopen"],
    hasInput: true,
    roles: COMMAND_ROLES["todos_reopen"]
  }),
  chatMessagesPost: defineCommand<ChatPostInput, ChatPostPayload>({
    field: "chat_messages_post",
    document: COMMAND_DOCS["chat_messages_post"],
    hasInput: true,
    roles: COMMAND_ROLES["chat_messages_post"]
  }),
  blobGamesStart: defineCommand<BlobStartInput, BlobGamePayload>({
    field: "blob_games_start",
    document: COMMAND_DOCS["blob_games_start"],
    hasInput: true,
    roles: COMMAND_ROLES["blob_games_start"]
  }),
  blobGamesMove: defineCommand<BlobMoveInput, BlobGamePayload>({
    field: "blob_games_move",
    document: COMMAND_DOCS["blob_games_move"],
    hasInput: true,
    roles: COMMAND_ROLES["blob_games_move"]
  }),
  blobGamesStartLevel: defineCommand<BlobStartLevelInput, BlobGamePayload>({
    field: "blob_games_start_level",
    document: COMMAND_DOCS["blob_games_start_level"],
    hasInput: true,
    roles: COMMAND_ROLES["blob_games_start_level"]
  }),
});

/**
 * todo.create -> GraphQL `todos_create`.
 */
export function todosCreate(input: TodoCreateInput, client: CommandClient): Promise<GqlResult<TodoCreatePayload>> {
  return executeCommand(client, COMMANDS.todosCreate, input);
}

/**
 * todo.complete -> GraphQL `todos_complete`.
 */
export function todosComplete(input: TodoCompleteInput, client: CommandClient): Promise<GqlResult<TodoStatusPayload>> {
  return executeCommand(client, COMMANDS.todosComplete, input);
}

/**
 * todo.archive -> GraphQL `todos_archive`.
 */
export function todosArchive(input: TodoArchiveInput, client: CommandClient): Promise<GqlResult<TodoStatusPayload>> {
  return executeCommand(client, COMMANDS.todosArchive, input);
}

/**
 * todo.force_archive -> GraphQL `todos_force_archive`.
 */
export function todosForceArchive(input: TodoForceArchiveInput, client: CommandClient): Promise<GqlResult<TodoForceArchivePayload>> {
  return executeCommand(client, COMMANDS.todosForceArchive, input);
}

/**
 * todo.rename -> GraphQL `todos_rename`.
 */
export function todosRename(input: TodoRenameInput, client: CommandClient): Promise<GqlResult<TodoRenamePayload>> {
  return executeCommand(client, COMMANDS.todosRename, input);
}

/**
 * todo.reopen -> GraphQL `todos_reopen`.
 */
export function todosReopen(input: TodoReopenInput, client: CommandClient): Promise<GqlResult<TodoStatusPayload>> {
  return executeCommand(client, COMMANDS.todosReopen, input);
}

/**
 * chat.post -> GraphQL `chat_messages_post`.
 */
export function chatMessagesPost(input: ChatPostInput, client: CommandClient): Promise<GqlResult<ChatPostPayload>> {
  return executeCommand(client, COMMANDS.chatMessagesPost, input);
}

/**
 * blob.start -> GraphQL `blob_games_start`.
 */
export function blobGamesStart(input: BlobStartInput, client: CommandClient): Promise<GqlResult<BlobGamePayload>> {
  return executeCommand(client, COMMANDS.blobGamesStart, input);
}

/**
 * blob.move -> GraphQL `blob_games_move`.
 */
export function blobGamesMove(input: BlobMoveInput, client: CommandClient): Promise<GqlResult<BlobGamePayload>> {
  return executeCommand(client, COMMANDS.blobGamesMove, input);
}

/**
 * blob.start_level -> GraphQL `blob_games_start_level`.
 */
export function blobGamesStartLevel(input: BlobStartLevelInput, client: CommandClient): Promise<GqlResult<BlobGamePayload>> {
  return executeCommand(client, COMMANDS.blobGamesStartLevel, input);
}

/** Commands pre-bound to a GraphQL client, with optional per-call policies. */
export type BoundCommands = BoundCommandSet<typeof COMMANDS>;
export type CommandBindOptions = BindCommandsOptions<typeof COMMANDS>;

/** Bind URL/auth/cache once, then call `commands.someCommand(input, options?)`. */
export function bindCommands(
  client: CommandClient,
  options: CommandBindOptions = {}
): BoundCommands {
  return bindDistributedCommands(client, COMMANDS, options);
}
