import assert from 'node:assert/strict';
import {
	mkdtemp,
	mkdir,
	readFile,
	realpath,
	rm,
	symlink,
	writeFile
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Worker } from 'node:worker_threads';
import test from 'node:test';

import {
	analyzeDistributedSvelteKitBoundaries,
	checkDistributedSvelteKit,
	distributedSvelteKit,
	distributedSvelteKitAliases,
	generateDistributedSvelteKit,
	generateDistributedSvelteKitLifecycle,
	validateDistributedSvelteKitBoundaryPlan
} from '../dist/sveltekit/vite.js';
import {
	distributedSvelteKit as distributedSvelteKitPublic,
	distributedSvelteKitAliases as distributedSvelteKitAliasesPublic
} from '../dist/sveltekit/public-vite.js';

test('public Vite adapters require the application lifecycle', () => {
	const previous = process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE;
	delete process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE;
	try {
		assert.throws(
			() => distributedSvelteKitPublic({ clients: [] }),
			/run the UI through `distributed dev` or `distributed build`/
		);
		assert.throws(
			() => distributedSvelteKitAliasesPublic({ clients: [] }),
			/run the UI through `distributed dev` or `distributed build`/
		);
	} finally {
		if (previous === undefined) {
			delete process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE;
		} else {
			process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE = previous;
		}
	}
});

const fakeDistributedSource = String.raw`
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  writeFileSync
} from 'node:fs';

const args = process.argv.slice(2);
appendFileSync(process.env.DISTRIBUTED_FAKE_LOG, JSON.stringify(args) + '\n');

if (args[0] === 'client-manifest') {
  process.stdout.write(JSON.stringify({ version: 7, source: args.at(-1) }));
  process.exit(0);
}

if (args[0] !== 'client') {
  process.stderr.write('unexpected fake command');
  process.exit(64);
}

const value = (name) => args[args.indexOf(name) + 1];
const surface = value('--surface') ?? value('--role');
if (surface === process.env.DISTRIBUTED_FAKE_FAIL_SURFACE) {
  process.stdout.write('sensitive schema and policy payload');
  process.stderr.write('synthetic compiler failure');
  process.exit(2);
}

const out = value('--out');
const documents = args.flatMap((arg, index) =>
  arg === '--documents' ? [args[index + 1]] : []
);
if (args.includes('--check')) {
  if (!existsSync(out + '/sveltekit.ts')) {
    process.stderr.write('missing generated entrypoint');
    process.exit(3);
  }
  process.stdout.write('fake client is current\n');
  process.exit(0);
}
const delay = Number(process.env.DISTRIBUTED_FAKE_DELAY_MS ?? 0);
if (delay > 0) await new Promise((resolve) => setTimeout(resolve, delay));
mkdirSync(out, { recursive: true });
writeFileSync(
  out + '/sveltekit.ts',
  '/** GENERATED by distributed client. Do not edit. */\nexport const surface = ' +
    JSON.stringify(surface) + ';\nexport const documents = ' +
    JSON.stringify(documents) + ';\n'
);
writeFileSync(
  out + '/manifest.json',
  JSON.stringify({ compiler_manifest_version: 1, operations: [] }) + '\n'
);
writeFileSync(
  out + '/islands.json',
  JSON.stringify({
    version: 1,
    schemaFingerprint: 'fake-schema-' + surface,
    protocolFingerprint: 'fake-protocol-' + surface,
    surface: { kind: 'application', name: surface },
    islands: documents.map((source, index) => ({
      version: 1,
      id: surface + '-island-' + index,
      operation: 'Operation' + index,
	  operationHash: 'hash-' + index,
	  modulePath: 'operations/operation-' + index + '.ts',
	  exportName: 'Operation_Operation' + index,
      source: { path: source, line: 1, column: 1 },
      directives: { load: true, live: false },
      liveCoverage: {
        requested: false,
        finite: false,
        kind: 'unknown'
      },
      variableSchema: {
        reference: 'hash-' + index + '#variable-codec-v2',
        codecVersion: 2,
        variables: []
      }
    }))
  }) + '\n'
);
process.stdout.write('generated fake client\n');
`;

async function fixture(t) {
	const root = await mkdtemp(join(tmpdir(), 'distributed-vite-test-'));
	const script = join(root, 'fake-distributed.mjs');
	const log = join(root, 'commands.log');
	await writeFile(script, fakeDistributedSource, 'utf8');
	await writeFile(log, '', 'utf8');
	await mkdir(join(root, 'src/routes/todos'), { recursive: true });
	await mkdir(join(root, 'src/routes/admin'), { recursive: true });
	await writeFile(
		join(root, 'src/routes/todos/+page.graphql'),
		'query Todos @load { todos { id } }\n'
	);
	await writeFile(
		join(root, 'src/routes/admin/+page.graphql'),
		'query AdminTodos @load { todos { id } }\n'
	);
	await writeFile(join(root, 'src/routes/todos/+page.svelte'), '<p>todos</p>\n');
	await writeFile(join(root, 'src/routes/admin/+page.svelte'), '<p>admin</p>\n');
	const previousLog = process.env.DISTRIBUTED_FAKE_LOG;
	const previousFailure = process.env.DISTRIBUTED_FAKE_FAIL_SURFACE;
	const previousDelay = process.env.DISTRIBUTED_FAKE_DELAY_MS;
	process.env.DISTRIBUTED_FAKE_LOG = log;
	delete process.env.DISTRIBUTED_FAKE_FAIL_SURFACE;
	delete process.env.DISTRIBUTED_FAKE_DELAY_MS;
	t.after(async () => {
		if (previousLog === undefined) delete process.env.DISTRIBUTED_FAKE_LOG;
		else process.env.DISTRIBUTED_FAKE_LOG = previousLog;
		if (previousFailure === undefined) {
			delete process.env.DISTRIBUTED_FAKE_FAIL_SURFACE;
		} else {
			process.env.DISTRIBUTED_FAKE_FAIL_SURFACE = previousFailure;
		}
		if (previousDelay === undefined) {
			delete process.env.DISTRIBUTED_FAKE_DELAY_MS;
		} else {
			process.env.DISTRIBUTED_FAKE_DELAY_MS = previousDelay;
		}
		await rm(root, { recursive: true, force: true });
	});
	return { root, script, log };
}

function clients() {
	return [
		{
			module: '$distributed',
			manifest: { args: ['client-manifest', '--entrypoint', 'user'] },
			surface: 'e2e-ui',
			documents: ['src/routes/todos/+page.graphql'],
			out: 'src/generated/user'
		},
		{
			module: '$distributed/admin',
			manifest: { args: ['client-manifest', '--entrypoint', 'admin'] },
			surface: 'e2e-ui-admin',
			documents: ['src/routes/admin/+page.graphql'],
			out: 'src/generated/admin'
		}
	];
}

function pluginOptions(root, script) {
	return {
		cwd: root,
		command: process.execPath,
		commandArgs: [script],
		clients: clients()
	};
}

async function commandLog(path) {
	const source = await readFile(path, 'utf8');
	return source
		.trim()
		.split('\n')
		.filter(Boolean)
		.map((line) => JSON.parse(line));
}

function islandInventory(source, operation = 'WidgetQuery', variables = []) {
	return {
		version: 1,
		schemaFingerprint: 'schema',
		protocolFingerprint: 'protocol',
		surface: { kind: 'application', name: 'test' },
		islands: [
			{
				version: 1,
				id: `island-${operation}`,
				operation,
				operationHash: `hash-${operation}`,
				modulePath: `operations/${operation.toLowerCase()}.ts`,
				exportName: `Operation_${operation}`,
				source: { path: source, line: 1, column: 1 },
				directives: { load: true, live: false },
				liveCoverage: {
					requested: false,
					finite: false,
					kind: 'unknown'
				},
				variableSchema: {
					reference: `hash-${operation}#variable-codec-v2`,
					codecVersion: 2,
					variables
				}
			}
		]
	};
}

test('boundary plans generate route-variable bindings and fail unprovable required values', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-variables-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes/items/[itemId]'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(join(root, 'src/routes/items/[itemId]/+page.svelte'), '<p>item</p>\n');
	const routeInventory = islandInventory(
		'src/routes/items/[itemId]/+page.graphql',
		'Item',
		[
			{ name: 'itemId', graphqlType: 'ID!' },
			{ name: 'limit', graphqlType: 'Int!', defaultValue: 25 },
			{ name: 'optional', graphqlType: 'String' }
		]
	);
	const planned = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [{ module: '$distributed', inventory: routeInventory }]
	});
	assert.deepEqual(planned[0].boundaries[0].islands[0].binding.sources, {
		itemId: { kind: 'route_param', name: 'itemId' },
		limit: { kind: 'omit' },
		optional: { kind: 'omit' }
	});
	assert.equal(planned[0].boundaries[0].islands[0].binding.discovery, 'route_param');
	const qualified = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed/public',
				inventory: islandInventory(
					'src/routes/items/[itemId]/+page.public.graphql',
					'PublicItem',
					[{ name: 'itemId', graphqlType: 'ID!' }]
				)
			}
		]
	});
	assert.equal(qualified[0].boundaries[0].route, '/items/[itemId]');
	assert.equal(qualified[0].boundaries[0].kind, 'page');

	const required = islandInventory(
		'src/routes/items/[itemId]/+page.graphql',
		'Item',
		[{ name: 'limit', graphqlType: 'Int!' }]
	);
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: required }]
		}),
		(error) => {
			assert.match(error.message, /\[distributed\.island\.variable_unprovable\]/);
			assert.match(error.message, /explicit binding, parent\/boundary query, client-only execution, or a better read root/);
			return true;
		}
	);
	const explicit = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed',
				inventory: required,
				explicitBoundaries: [
					{
						operation: 'Item',
						route: '/items/[itemId]',
						kind: 'page',
						variables: { limit: { kind: 'constant', value: 20 } }
					}
				]
			}
		]
	});
	assert.equal(explicit[0].boundaries[0].islands[0].binding.discovery, 'explicit');
	assert.deepEqual(explicit[0].boundaries[0].islands[0].binding.sources, {
		limit: { kind: 'constant', value: 20 }
	});

	await writeFile(join(root, 'package.json'), '{"type":"module"}\n');
	const sidecar = join(
		root,
		'src/routes/items/[itemId]/+page.graphql.bindings.js'
	);
	const helper = pathToFileURL(join(process.cwd(), 'dist/sveltekit/index.js')).href;
	await writeFile(
		sidecar,
		`import { defineGraphqlIslandBindings, searchParam } from ${JSON.stringify(helper)};\n` +
			`export default defineGraphqlIslandBindings({ limit: searchParam('pageSize') });\n`
	);
	const colocated = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [{ module: '$distributed', inventory: required }]
	});
	assert.deepEqual(colocated[0].boundaries[0].islands[0].binding.sources, {
		limit: { kind: 'search_param', name: 'pageSize', mode: 'first' }
	});
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: required,
					explicitBoundaries: [
						{
							operation: 'Item',
							route: '/items/[itemId]',
							kind: 'page',
							variables: { limit: { kind: 'constant', value: 20 } }
						}
					]
				}
			]
		}),
		/\[distributed\.island\.variable_binding_conflict\]/
	);
	await rm(sidecar);
	for (const hostile of [
		{ kind: 'trusted_session', path: ['__proto__'] },
		{ kind: 'query_result', path: ['items', 'limit'] }
	]) {
		await assert.rejects(
			analyzeDistributedSvelteKitBoundaries({
				cwd: root,
				clients: [
					{
						module: '$distributed',
						inventory: required,
						explicitBoundaries: [
							{
								operation: 'Item',
								route: '/items/[itemId]',
								kind: 'page',
								variables: { limit: hostile }
							}
						]
					}
				]
			}),
			(error) => {
				assert.match(error.message, /\[distributed\.island\.variable_source_invalid\]/);
				assert.match(error.message, /src\/routes\/items\/\[itemId\]\/\+page\.graphql:1:1/);
				assert.match(error.message, /boundary \/items\/\[itemId\]/);
				assert.doesNotMatch(error.message, /items\.limit|accessToken|authorization/i);
				assert.match(error.message, /invalid|unsupported/);
				return true;
			}
		);
	}
	await writeFile(sidecar, 'export default {};\n');
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: required }]
		}),
		/\[distributed\.island\.bindings_invalid\]/
	);
});

test('Svelte boundary analysis promotes component islands to their nearest static page or layout', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-test-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes/orders'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(
		join(root, 'src/lib/OrderList.svelte'),
		'<script>import Row from "./Row.svelte";</script><Row />\n'
	);
	await writeFile(
		join(root, 'src/lib/Row.svelte'),
		'<p>row</p>\n'
	);
	await writeFile(
		join(root, 'src/routes/orders/+page.svelte'),
		'<script>import OrderList from "$lib/OrderList.svelte";</script><OrderList />\n'
	);
	await writeFile(join(root, 'src/routes/orders/+layout.svelte'), '<slot />\n');

	const analyze = () =>
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: islandInventory('src/lib/Row.graphql')
				}
			]
		});
	const pagePlan = (await analyze())[0];
	assert.deepEqual(
		pagePlan.boundaries.map(({ id, islands }) => [id, islands.map(({ operation }) => operation)]),
		[['page:/orders', ['WidgetQuery']]],
		'static traversal places one occurrence on the importing page'
	);
	assert.equal(pagePlan.boundaries[0].islands[0].reason, 'static_component_import');
	assert.equal(pagePlan.boundaries[0].islands[0].conservative, true);
	await writeFile(
		join(root, 'src/routes/+layout.svelte'),
		'<script>import OrderList from "$lib/OrderList.svelte";</script><OrderList /><slot />\n'
	);
	const repeatedPlan = (await analyze())[0];
	assert.deepEqual(
		repeatedPlan.boundaries.map(({ id }) => id),
		['layout:/', 'page:/orders'],
		'nested boundaries retain each statically owned occurrence for runtime deduplication'
	);

	await writeFile(join(root, 'src/routes/orders/+page.svelte'), '<p>page</p>\n');
	await writeFile(join(root, 'src/routes/+layout.svelte'), '<slot />\n');
	await writeFile(
		join(root, 'src/routes/orders/+layout.svelte'),
		'<script>import OrderList from "$lib/OrderList.svelte";</script><OrderList /><slot />\n'
	);
	const layoutPlan = (await analyze())[0];
	assert.deepEqual(
		layoutPlan.boundaries.map(({ id }) => id),
		['layout:/orders'],
		'moving the same component changes placement without changing its island identity'
	);
	assert.equal(
		layoutPlan.boundaries[0].islands[0].islandId,
		pagePlan.boundaries[0].islands[0].islandId
	);
});

test('Svelte boundary analysis recognizes named and reset page and layout roots', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-reset-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes/reset-page'), { recursive: true });
	await mkdir(join(root, 'src/routes/reset-layout'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(join(root, 'src/lib/Card.svelte'), '<p>card</p>\n');
	await writeFile(
		join(root, 'src/routes/reset-page/+page@.svelte'),
		'<script>import Card from "$lib/Card.svelte";</script><Card />\n'
	);
	await writeFile(
		join(root, 'src/routes/reset-layout/+layout@(app).svelte'),
		'<slot />\n'
	);

	const page = islandInventory('src/routes/reset-page/+page.graphql', 'ResetPage');
	const layout = islandInventory('src/routes/reset-layout/+layout.graphql', 'ResetLayout');
	const card = islandInventory('src/lib/Card.graphql', 'ResetCard');
	const [plan] = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed',
				inventory: {
					...page,
					islands: [...page.islands, ...layout.islands, ...card.islands]
				}
			}
		]
	});

	assert.deepEqual(
		plan.boundaries.map(({ id, source, islands }) => [
			id,
			source,
			islands.map(({ operation, reason }) => [operation, reason])
		]),
		[
			[
				'layout:/reset-layout',
				'src/routes/reset-layout/+layout@(app).svelte',
				[['ResetLayout', 'route_document']]
			],
			[
				'page:/reset-page',
				'src/routes/reset-page/+page@.svelte',
				[
					['ResetCard', 'static_component_import'],
					['ResetPage', 'route_document']
				]
			]
		]
	);
	assert.deepEqual(plan.unplaced, []);
});

test('explicit boundaries do not hide dynamic island reachability on other routes', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-explicit-scope-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes/explicit'), { recursive: true });
	await mkdir(join(root, 'src/routes/dynamic'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(join(root, 'src/lib/Card.svelte'), '<p>card</p>\n');
	await writeFile(join(root, 'src/routes/explicit/+page.svelte'), '<p>explicit</p>\n');
	await writeFile(
		join(root, 'src/routes/dynamic/+page.svelte'),
		'<script>const Card = import("$lib/Card.svelte");</script><p>dynamic</p>\n'
	);

	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: islandInventory('src/lib/Card.graphql', 'CardQuery'),
					explicitBoundaries: [
						{ operation: 'CardQuery', route: '/explicit', kind: 'page' }
					]
				}
			]
		}),
		(error) => {
			assert.match(error.message, /\[distributed\.island\.dynamic_load\]/);
			assert.match(error.message, /boundary \/dynamic/);
			return true;
		}
	);

	const [allowed] = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed',
				inventory: islandInventory('src/lib/Card.graphql', 'CardQuery'),
				explicitBoundaries: [
					{ operation: 'CardQuery', route: '/dynamic', kind: 'page' }
				]
			}
		]
	});
	assert.deepEqual(
		allowed.boundaries.map(({ id, islands }) => [
			id,
			islands.map(({ operation, reason }) => [operation, reason])
		]),
		[['page:/dynamic', [['CardQuery', 'explicit']]]]
	);
});

test('Svelte boundary analysis owns route documents and fails closed for dynamic load reachability', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-negative-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes/inbox'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(join(root, 'src/routes/inbox/+layout.svelte'), '<slot />\n');
	await writeFile(
		join(root, 'src/routes/inbox/+page.svelte'),
		'<script>const Card = import("$lib/Card.svelte");</script><p>inbox</p>\n'
	);
	await writeFile(join(root, 'src/lib/Card.svelte'), '<p>card</p>\n');
	const route = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed',
				inventory: islandInventory('src/routes/inbox/+layout.graphql', 'Inbox')
			}
		]
	});
	assert.deepEqual(route[0].boundaries.map(({ id }) => id), ['layout:/inbox']);
	assert.equal(route[0].boundaries[0].islands[0].reason, 'route_document');

	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: islandInventory('src/lib/Card.graphql', 'CardQuery')
				}
			]
		}),
		(error) => {
			assert.match(error.message, /\[distributed\.island\.dynamic_load\]/);
			assert.match(error.message, /src\/routes\/inbox\/\+page\.svelte:1:/);
			assert.doesNotMatch(error.message, /<script>|<p>/);
			return true;
		}
	);
	await writeFile(
		join(root, 'src/routes/inbox/+page.svelte'),
		'<script>const target = "$lib/Card.svelte"; const Card = import(target);</script><p>inbox</p>\n'
	);
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: islandInventory('src/lib/Card.graphql', 'CardQuery')
				}
			]
		}),
		/\[distributed\.island\.dynamic_opaque\]/
	);
	const conflicting = islandInventory('src/lib/Card.graphql', 'CardQuery');
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: {
						...conflicting,
						islands: [
							...conflicting.islands,
							...islandInventory('src/lib/Card.gql', 'OtherCardQuery').islands
						]
					}
				}
			]
		}),
		/\[distributed\.island\.sibling_conflict\]/
	);
});

test('Svelte boundary analysis rejects unresolved aliases and cross-surface island ownership', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-surface-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(
		join(root, 'src/routes/+page.svelte'),
		'<script>import Card from "$widgets/Card.svelte";</script><Card />\n'
	);
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: islandInventory('src/routes/+page.graphql') }]
		}),
		/\[distributed\.island\.alias_unresolved\]/
	);
	await mkdir(join(root, 'src/widgets'), { recursive: true });
	await writeFile(join(root, 'src/widgets/Card.svelte'), '<p>card</p>\n');
	const aliased = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		aliases: { $widgets: 'src/widgets' },
		clients: [
			{ module: '$distributed', inventory: islandInventory('src/widgets/Card.graphql') }
		]
	});
	assert.deepEqual(aliased[0].boundaries.map(({ id }) => id), ['page:/']);

	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{ module: '$distributed', inventory: islandInventory('src/lib/Card.graphql') },
				{ module: '$distributed/admin', inventory: islandInventory('src/lib/Card.graphql') }
			]
		}),
		/\[distributed\.island\.cross_surface\]/
	);
	await writeFile(join(root, 'src/routes/+page.svelte'), '<p>page</p>\n');
	const explicit = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed',
				inventory: islandInventory('src/lib/Missing.graphql', 'MissingQuery'),
				explicitBoundaries: [
					{ operation: 'MissingQuery', route: '/', kind: 'page' }
				]
			}
		]
	});
	assert.equal(explicit[0].boundaries[0].islands[0].reason, 'explicit');
});

test('boundary diagnostics reject cycles, stale plans, and unbounded layout live while bounded remedies pass', async (t) => {
	const root = await mkdtemp(join(tmpdir(), 'distributed-boundary-matrix-'));
	t.after(() => rm(root, { recursive: true, force: true }));
	await mkdir(join(root, 'src/routes'), { recursive: true });
	await mkdir(join(root, 'src/lib'), { recursive: true });
	await writeFile(
		join(root, 'src/routes/+layout.svelte'),
		'<script>import LiveList from "$lib/LiveList.svelte";</script><LiveList /><slot />\n'
	);
	await writeFile(join(root, 'src/routes/+page.svelte'), '<p>page</p>\n');
	await writeFile(join(root, 'src/lib/LiveList.svelte'), '<p>live</p>\n');
	const unbounded = islandInventory('src/lib/LiveList.graphql', 'LiveList');
	unbounded.islands[0].directives.live = true;
	unbounded.islands[0].liveCoverage = {
		requested: true,
		finite: false,
		kind: 'unknown'
	};
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: unbounded }]
		}),
		(error) => {
			assert.match(error.message, /\[distributed\.island\.layout_live_unbounded\]/);
			assert.match(error.message, /src\/lib\/LiveList\.graphql:1:1/);
			assert.match(error.message, /compiler-proved limit|bounded boundary-owned query|client-only/);
			assert.doesNotMatch(error.message, /<script>|<LiveList/);
			return true;
		}
	);

	const finite = structuredClone(unbounded);
	finite.islands[0].liveCoverage = {
		requested: true,
		finite: true,
		kind: 'offset',
		maxItems: 25
	};
	const finitePlan = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [{ module: '$distributed', inventory: finite }]
	});
	assert.equal(finitePlan[0].boundaries[0].kind, 'layout');
	assert.deepEqual(finitePlan[0].boundaries[0].islands[0].liveCoverage, {
		requested: true,
		finite: true,
		kind: 'offset',
		maxItems: 25
	});

	await writeFile(
		join(root, 'src/routes/+layout.svelte'),
		'<script>import A from "$lib/A.svelte";</script><A /><slot />\n'
	);
	await writeFile(
		join(root, 'src/lib/A.svelte'),
		'<script>import B from "./B.svelte";</script><B />\n'
	);
	await writeFile(
		join(root, 'src/lib/B.svelte'),
		'<script>import A from "./A.svelte";</script><A />\n'
	);
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [
				{
					module: '$distributed',
					inventory: islandInventory('src/lib/B.graphql', 'CyclicIsland')
				}
			]
		}),
		(error) => {
			assert.match(error.message, /\[distributed\.island\.component_cycle\]/);
			assert.match(error.message, /src\/lib\/[AB]\.svelte:1:/);
			assert.match(error.message, /explicit boundary-owned query|client-only/);
			return true;
		}
	);
	await writeFile(join(root, 'src/lib/Conditional.svelte'), '<p>conditional</p>\n');
	await writeFile(
		join(root, 'src/routes/+layout.svelte'),
		'<script>import Conditional from "$lib/Conditional.svelte"; const enabled = false;</script>{#if enabled}<Conditional />{/if}<slot />\n'
	);
	const conditionalPlan = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [
			{
				module: '$distributed',
				inventory: islandInventory('src/lib/Conditional.graphql', 'ConditionalIsland')
			}
		]
	});
	assert.equal(
		conditionalPlan[0].boundaries[0].islands[0].conservative,
		true,
		'a statically imported bounded conditional is conservatively promoted'
	);

	const clientOnly = islandInventory('src/lib/Missing.graphql', 'ClientOnly');
	clientOnly.islands[0].directives.load = false;
	const clientOnlyPlan = await analyzeDistributedSvelteKitBoundaries({
		cwd: root,
		clients: [{ module: '$distributed', inventory: clientOnly }]
	});
	assert.deepEqual(clientOnlyPlan[0].boundaries, []);
	assert.deepEqual(clientOnlyPlan[0].unplaced, []);

	const stale = islandInventory('src/lib/Missing.graphql', 'StaleIsland');
	stale.islands[0].version = 2;
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: stale }]
		}),
		/\[distributed\.island\.version_unsupported\] src\/lib\/Missing\.graphql:1:1/
	);
	const staleCodec = islandInventory('src/lib/Missing.graphql', 'StaleCodec');
	staleCodec.islands[0].variableSchema = {
		...staleCodec.islands[0].variableSchema,
		reference: `hash-StaleCodec#variable-codec-v1`,
		codecVersion: 1
	};
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: staleCodec }]
		}),
		/\[distributed\.island\.version_unsupported\] src\/lib\/Missing\.graphql:1:1/
	);
	const malformedVariables = islandInventory(
		'src/lib/Missing.graphql',
		'MalformedVariables'
	);
	malformedVariables.islands[0].variableSchema.variables = [{}];
	await assert.rejects(
		analyzeDistributedSvelteKitBoundaries({
			cwd: root,
			clients: [{ module: '$distributed', inventory: malformedVariables }]
		}),
		/\[distributed\.island\.version_unsupported\] src\/lib\/Missing\.graphql:1:1/
	);
	assert.throws(
		() => validateDistributedSvelteKitBoundaryPlan(
			{ version: 2, module: '$distributed', boundaries: [], unplaced: [] },
			'$distributed'
		),
		/\[distributed\.island\.boundary_plan_invalid\]/
	);
});

test('Vite maps analyzed boundary plans by module rather than declaration order', async (t) => {
	const { root, script } = await fixture(t);
	const options = {
		...pluginOptions(root, script),
		clients: [...clients()].reverse()
	};

	await generateDistributedSvelteKit(options);

	const admin = await readFile(
		join(root, 'src/generated/admin/boundaries.ts'),
		'utf8'
	);
	const user = await readFile(
		join(root, 'src/generated/user/boundaries.ts'),
		'utf8'
	);
	assert.match(admin, /"module": "\$distributed\/admin"/);
	assert.match(admin, /src\/routes\/admin\/\+page\.graphql/);
	assert.match(user, /"module": "\$distributed"/);
	assert.match(user, /src\/routes\/todos\/\+page\.graphql/);
	await checkDistributedSvelteKit(options);
});

test('lifecycle generation writes only to the immutable candidate stage', async (t) => {
	const { root, script } = await fixture(t);
	const stage = join(root, '.distributed/lifecycle-stage');
	await mkdir(stage, { recursive: true });

	await generateDistributedSvelteKitLifecycle(pluginOptions(root, script), {
		projectRoot: root,
		stage
	});

	assert.match(
		await readFile(join(stage, 'src/generated/user/sveltekit.ts'), 'utf8'),
		/e2e-ui/
	);
	await assert.rejects(
		readFile(join(root, 'src/generated/user/sveltekit.ts')),
		(error) => error?.code === 'ENOENT'
	);
	assert.match(
		await readFile(
			join(
				stage,
				'.svelte-kit/distributed/clients',
				Buffer.from('$distributed').toString('base64url'),
				'boundaries.json'
			),
			'utf8'
		),
		/"module": "\$distributed"/
	);
});

test('Vite compiles and resolves isolated user/admin physical entrypoints', async (t) => {
	const { root, script, log } = await fixture(t);
	const options = pluginOptions(root, script);
	const plugin = distributedSvelteKit(options);
	await plugin.configResolved({ root });

	const aliases = distributedSvelteKitAliases({
		cwd: root,
		clients: options.clients
	});
	assert.deepEqual(aliases, {
		'$distributed/admin': join(root, 'src/generated/admin/sveltekit.ts'),
		$distributed: join(root, 'src/generated/user/sveltekit.ts')
	});

	const userId = plugin.resolveId('$distributed');
	const adminId = plugin.resolveId('$distributed/admin');
	assert.match(userId, /^\0@hops-ops\/distributed:sveltekit:/);
	assert.match(adminId, /^\0@hops-ops\/distributed:sveltekit:/);
	assert.match(
		plugin.load(userId),
		new RegExp(
			JSON.stringify(join(root, 'src/generated/user/sveltekit.ts')).replace(
				/[.*+?^${}()|[\]\\]/g,
				'\\$&'
			)
		)
	);
	assert.match(
		await readFile(join(root, 'src/generated/admin/sveltekit.ts'), 'utf8'),
		/e2e-ui-admin/
	);
	const userBoundaryPath = join(
		root,
		'.svelte-kit/distributed/clients',
		Buffer.from('$distributed').toString('base64url'),
		'boundaries.json'
	);
	const userBoundaries = JSON.parse(await readFile(userBoundaryPath, 'utf8'));
	assert.deepEqual(
		userBoundaries.boundaries.map(({ id }) => id),
		['page:/todos'],
		'adapter generation commits an inspectable boundary plan beside compiler output'
	);

	const initial = await commandLog(log);
	assert.deepEqual(
		initial.map((args) => args[0]),
		['client-manifest', 'client', 'client-manifest', 'client']
	);
	assert.deepEqual(
		initial
			.filter((args) => args[0] === 'client')
			.map((args) => args[args.indexOf('--surface') + 1]),
		['e2e-ui', 'e2e-ui-admin']
	);

	const added = [];
	const messages = [];
	const invalidated = [];
	const modules = new Map([
		[userId, { id: userId }],
		[adminId, { id: adminId }]
	]);
	const server = {
		watcher: { add: (paths) => added.push(paths) },
		ws: { send: (message) => messages.push(message) },
		moduleGraph: {
			getModuleById: (id) => modules.get(id),
			invalidateModule: (module) => invalidated.push(module.id)
		}
	};
	plugin.configureServer(server);
	assert.ok(added.flat().some((path) => path.includes('src/routes/')));

	const change = {
		file: join(root, 'src/routes/todos/+page.graphql'),
		server
	};
	await Promise.all([
		plugin.handleHotUpdate(change),
		plugin.handleHotUpdate(change),
		plugin.handleHotUpdate(change)
	]);
	const afterChanges = await commandLog(log);
	assert.equal(
		afterChanges.length,
		12,
		'three overlapping notifications coalesce into one active and one trailing transaction'
	);
	assert.deepEqual(invalidated, [userId, adminId]);
	assert.equal(
		messages.filter((message) => message.type === 'full-reload').length,
		1,
		'one successful coalesced generation issues one full reload'
	);
	assert.equal(
		await plugin.handleHotUpdate({
			file: join(root, 'src/generated/user/ignored.graphql'),
			server
		}),
		undefined,
		'generated output changes never trigger the compiler'
	);
	await plugin.closeBundle();

	const beforeCheck = await readFile(
		join(root, 'src/generated/user/sveltekit.ts'),
		'utf8'
	);
	await rm(join(root, '.svelte-kit'), { recursive: true, force: true });
	await checkDistributedSvelteKit(options);
	assert.equal(
		await readFile(join(root, 'src/generated/user/sveltekit.ts'), 'utf8'),
		beforeCheck,
		'the shared check runner validates durable output without requiring SvelteKit build state'
	);
	await generateDistributedSvelteKit(options);
	assert.match(
		await readFile(join(root, 'src/generated/user/sveltekit.ts'), 'utf8'),
		/todos/
	);
	await writeFile(
		join(
			root,
			'.svelte-kit/distributed/clients',
			Buffer.from('$distributed').toString('base64url'),
			'boundaries.json'
		),
		'{not-json}\n'
	);
	await assert.rejects(
		checkDistributedSvelteKit(options),
		/\[distributed\.island\.boundary_plan_invalid\]/,
		'existing adapter build state still fails closed when it is invalid'
	);
	await generateDistributedSvelteKit(options);
	await writeFile(join(root, 'src/routes/todos/+page.svelte'), '<p>changed</p>\n');
	const pluginAfterGenerate = distributedSvelteKit(options);
	await pluginAfterGenerate.configResolved({ root });
	const svelteChangeStart = (await commandLog(log)).length;
	await pluginAfterGenerate.watchChange(join(root, 'src/routes/todos/+page.svelte'));
	assert.equal(
		(await commandLog(log)).length,
		svelteChangeStart + 4,
		'Svelte import changes participate in the same coherent generation transaction'
	);
	await pluginAfterGenerate.closeBundle();
});

test('same-process Vite instances coalesce one shared startup generation', async (t) => {
	const { root, script, log } = await fixture(t);
	process.env.DISTRIBUTED_FAKE_DELAY_MS = '75';
	const options = pluginOptions(root, script);
	const first = distributedSvelteKit(options);
	const second = distributedSvelteKit(options);

	await Promise.all([
		first.configResolved({ root }),
		second.configResolved({ root })
	]);
	assert.deepEqual(
		(await commandLog(log)).map((args) => args[0]),
		[
			'client-manifest',
			'client',
			'client-manifest',
			'client'
		],
		'identical plugin instances compile one startup generation'
	);

	await first.closeBundle();
	await second.watchChange(join(root, 'src/routes/todos/+page.graphql'));
	assert.equal(
		(await commandLog(log)).length,
		8,
		'the remaining instance retains the shared project lock'
	);
	await second.closeBundle();
	await checkDistributedSvelteKit(options);
});

test('supervised Vite defers generated-client compilation to the lifecycle', async (t) => {
	const { root, script, log } = await fixture(t);
	const lifecycleRoot = await mkdtemp(join(tmpdir(), 'distributed-supervisor-'));
	t.after(() => rm(lifecycleRoot, { recursive: true, force: true }));
	const previousLifecycle = process.env.DISTRIBUTED_LIFECYCLE_DIR;
	const previousClientOwnership = process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE;
	const previousProjectRoot = process.env.DISTRIBUTED_LIFECYCLE_PROJECT_ROOT;
	const generation = `sha256:${'a'.repeat(64)}`;
	const activePointer = join(lifecycleRoot, 'active.json');
	await mkdir(join(lifecycleRoot, 'generations', generation, 'src/generated/user'), {
		recursive: true
	});
	await writeFile(
		join(lifecycleRoot, 'generations', generation, 'src/generated/user/sveltekit.ts'),
		'export const supervised = true;\n'
	);
	await writeFile(
		activePointer,
		JSON.stringify({ schema_version: 1, generation_id: generation })
	);
	process.env.DISTRIBUTED_LIFECYCLE_DIR = lifecycleRoot;
	process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE = '1';
	process.env.DISTRIBUTED_LIFECYCLE_PROJECT_ROOT = root;
	t.after(() => {
		if (previousLifecycle === undefined) {
			delete process.env.DISTRIBUTED_LIFECYCLE_DIR;
		} else {
			process.env.DISTRIBUTED_LIFECYCLE_DIR = previousLifecycle;
		}
		if (previousClientOwnership === undefined) {
			delete process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE;
		} else {
			process.env.DISTRIBUTED_LIFECYCLE_OWNS_CLIENT_COMPILE = previousClientOwnership;
		}
		if (previousProjectRoot === undefined) {
			delete process.env.DISTRIBUTED_LIFECYCLE_PROJECT_ROOT;
		} else {
			process.env.DISTRIBUTED_LIFECYCLE_PROJECT_ROOT = previousProjectRoot;
		}
	});
	const frameworkDist = join(root, 'node_modules/@hops-ops/distributed/dist');
	await mkdir(join(frameworkDist, 'replica'), { recursive: true });
	const plugin = distributedSvelteKit(pluginOptions(root, script));
	await plugin.configResolved({ root });
	const lazyEntry = join(await realpath(frameworkDist), 'replica/lazy.js');
	assert.equal(plugin.resolveId('@hops-ops/distributed/replica/lazy'), lazyEntry);
	const aliases = distributedSvelteKitAliases({ cwd: root, clients: [clients()[0]] });
	assert.equal(aliases['@hops-ops/distributed/replica/lazy'], lazyEntry);
	await writeFile(activePointer, 'not-json');
	assert.equal(
		plugin.resolveId('./ordinary-relative-import.js', join(root, 'src/app.ts')),
		undefined,
		'unrelated imports do not read lifecycle generation state'
	);
	await writeFile(
		activePointer,
		JSON.stringify({ schema_version: 1, generation_id: generation })
	);
	const added = [];
	const invalidated = [];
	const websocketMessages = [];
	const server = {
		watcher: { add: (paths) => added.push(paths) },
		ws: { send: (message) => websocketMessages.push(message) },
		moduleGraph: {
			getModuleById: (id) => ({ id }),
			invalidateModule: (module) => invalidated.push(module.id)
		}
	};
	plugin.configureServer(server);

	const startupCommands = await commandLog(log);
	assert.deepEqual(
		startupCommands,
		[],
		'lifecycle-owned startup serves the generation already built by the supervisor'
	);
	assert.deepEqual(added, [await realpath(activePointer)]);
	const userId = plugin.resolveId('$distributed');
	const adminId = plugin.resolveId('$distributed/admin');
	assert.match(
		plugin.load(userId),
		new RegExp(
			JSON.stringify(
				join(
					lifecycleRoot,
					'generations',
					generation,
					'src/generated/user/sveltekit.ts'
				)
			).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
		)
	);
	assert.deepEqual(
		await plugin.handleHotUpdate({ file: activePointer, server }),
		[]
	);
	assert.deepEqual(invalidated, [userId, adminId]);
	assert.deepEqual(
		websocketMessages,
		[],
		'the browser lifecycle remains the sole coordinated reload authority'
	);
	assert.deepEqual(
		await plugin.handleHotUpdate({
			file: join(root, 'src/routes/todos/+page.graphql'),
			server
		}),
		[]
	);
	await plugin.watchChange(join(root, 'src/routes/admin/+page.graphql'));
	assert.deepEqual(await commandLog(log), startupCommands);
	assert.deepEqual(
		await plugin.handleHotUpdate({
			file: join(root, 'src/routes/todos/+page.graphql.bindings.js'),
			server
		}),
		[]
	);
	assert.deepEqual(
		await commandLog(log),
		startupCommands,
		'binding sidecars are held for the same lifecycle-owned restart as documents'
	);
	await plugin.closeBundle();
});

test('SvelteKit config-probe workers never compile or contend for the project lock', async (t) => {
	const { root, script, log } = await fixture(t);
	const options = pluginOptions(root, script);
	const moduleUrl = new URL('../dist/sveltekit/vite.js', import.meta.url).href;
	const resolved = await new Promise((resolvePromise, rejectPromise) => {
		const worker = new Worker(
			String.raw`
const { parentPort, workerData } = require('node:worker_threads');
(async () => {
  const { distributedSvelteKit } = await import(workerData.moduleUrl);
  const plugin = distributedSvelteKit(workerData.options);
  await plugin.configResolved({ root: workerData.options.cwd });
  const resolved = plugin.resolveId('$distributed');
  await plugin.closeBundle();
  parentPort.postMessage({ resolved });
})().catch((error) => {
  parentPort.postMessage({ error: error?.stack ?? String(error) });
});
`,
			{
				eval: true,
				env: { ...process.env, SVELTEKIT_FORK: 'true' },
				workerData: { moduleUrl, options }
			}
		);
		worker.once('message', (message) => {
			if (message?.error !== undefined) {
				rejectPromise(new Error(message.error));
			} else {
				resolvePromise(message.resolved);
			}
		});
		worker.once('error', rejectPromise);
	});

	assert.match(resolved, /^\0@hops-ops\/distributed:sveltekit:/);
	assert.deepEqual(await commandLog(log), []);
});

test('multi-surface failure leaves old outputs intact and redacts stdout', async (t) => {
	const { root, script } = await fixture(t);
	const userOut = join(root, 'src/generated/user');
	const adminOut = join(root, 'src/generated/admin');
	await mkdir(userOut, { recursive: true });
	await mkdir(adminOut, { recursive: true });
	await writeFile(join(userOut, 'sveltekit.ts'), 'old-user\n');
	await writeFile(join(adminOut, 'sveltekit.ts'), 'old-admin\n');
	process.env.DISTRIBUTED_FAKE_FAIL_SURFACE = 'e2e-ui-admin';

	const plugin = distributedSvelteKit(pluginOptions(root, script));
	await assert.rejects(
		plugin.configResolved({ root }),
		(error) => {
			assert.match(error.message, /synthetic compiler failure/);
			assert.match(error.message, /argv: \[/);
			assert.match(error.message, new RegExp(`cwd: ${root}`));
			assert.doesNotMatch(error.message, /sensitive schema and policy payload/);
			return true;
		}
	);
	assert.equal(await readFile(join(userOut, 'sveltekit.ts'), 'utf8'), 'old-user\n');
	assert.equal(
		await readFile(join(adminOut, 'sveltekit.ts'), 'utf8'),
		'old-admin\n'
	);
	await plugin.closeBundle();
});

test('configuration rejects ambiguous surfaces, aliases, and output containment hazards', async (t) => {
	const { root, script } = await fixture(t);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					...clients(),
					{
						...clients()[0],
						module: '$distributed/nested',
						out: 'src/generated/user/nested'
					}
				]
			}),
		/outputs must not overlap/
	);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					{
						...clients()[0],
						surface: 'e2e-ui',
						role: 'user'
					}
				]
			}),
		/exactly one of role or surface/
	);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [clients()[0], { ...clients()[1], module: '$distributed' }]
			}),
		/duplicate Distributed client module/
	);

	const outside = await mkdtemp(join(tmpdir(), 'distributed-vite-outside-'));
	t.after(() => rm(outside, { recursive: true, force: true }));
	await symlink(outside, join(root, 'linked-output'));
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					{
						...clients()[0],
						out: 'linked-output/user'
					}
				]
			}),
		/contains symlink component|resolves outside project root/,
		'language-tool aliases reject an escaping symlink before Vite starts'
	);
	const plugin = distributedSvelteKit({
		...pluginOptions(root, script),
		clients: [
			{
				...clients()[0],
				out: 'linked-output/user'
			}
		]
	});
	await assert.rejects(
		plugin.configResolved({ root }),
		/contains symlink component|resolves outside project root/
	);
	await plugin.closeBundle();

	await mkdir(join(root, 'src/generated/shared'), { recursive: true });
	await symlink(
		join(root, 'src/generated/shared'),
		join(root, 'src/generated/shared-alias')
	);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					{ ...clients()[0], out: 'src/generated/shared/user' },
					{
						...clients()[1],
						out: 'src/generated/shared-alias/user'
					}
				]
			}),
		/contains symlink component|physically overlap/,
		'two lexical outputs cannot alias one physical authorization surface'
	);
});

test('gql changes regenerate and cancellation before commit preserves old outputs', async (t) => {
	const { root, script, log } = await fixture(t);
	const options = pluginOptions(root, script);
	const plugin = distributedSvelteKit(options);
	await plugin.configResolved({ root });
	const server = {
		watcher: { add() {} },
		ws: { send() {} },
		moduleGraph: {
			getModuleById: () => undefined,
			invalidateModule() {}
		}
	};
	const gql = join(root, 'src/routes/todos/extra.gql');
	await writeFile(gql, 'query Extra { todos { id } }\n');
	const beforeGql = (await commandLog(log)).length;
	await plugin.handleHotUpdate({ file: gql, server });
	assert.equal(
		(await commandLog(log)).length,
		beforeGql + 4,
		'legacy .gql inputs receive the same compiler watch lifecycle'
	);
	await writeFile(join(root, 'package.json'), '{"type":"module"}\n');
	const bindings = join(root, 'src/routes/todos/+page.graphql.bindings.js');
	const helper = pathToFileURL(join(process.cwd(), 'dist/sveltekit/index.js')).href;
	await writeFile(
		bindings,
		`import { defineGraphqlIslandBindings } from ${JSON.stringify(helper)};\n` +
			'export default defineGraphqlIslandBindings({});\n'
	);
	const beforeBindings = (await commandLog(log)).length;
	await plugin.handleHotUpdate({ file: bindings, server });
	assert.equal(
		(await commandLog(log)).length,
		beforeBindings + 4,
		'colocated GraphQL binding changes receive the compiler watch lifecycle'
	);
	await plugin.closeBundle();

	const userOut = join(root, 'src/generated/user');
	const adminOut = join(root, 'src/generated/admin');
	await writeFile(join(userOut, 'sveltekit.ts'), 'stable-user\n');
	await writeFile(join(adminOut, 'sveltekit.ts'), 'stable-admin\n');
	process.env.DISTRIBUTED_FAKE_DELAY_MS = '5000';
	const cancelling = distributedSvelteKit(options);
	const startup = cancelling.configResolved({ root });
	await waitFor(async () => (await commandLog(log)).at(-1)?.[0] === 'client');
	await cancelling.closeBundle();
	await assert.rejects(startup);
	assert.equal(
		await readFile(join(userOut, 'sveltekit.ts'), 'utf8'),
		'stable-user\n'
	);
	assert.equal(
		await readFile(join(adminOut, 'sveltekit.ts'), 'utf8'),
		'stable-admin\n'
	);
});

test('overflowing compiler output is bounded and force-killed', async (t) => {
	const { root, log } = await fixture(t);
	const script = join(root, 'overflow.mjs');
	await writeFile(
		script,
		`process.on('SIGTERM', () => {});\n` +
			`const chunk = 'x'.repeat(1024 * 1024);\n` +
			`for (let i = 0; i < 20; i += 1) process.stdout.write(chunk);\n` +
			`setInterval(() => {}, 1000);\n`,
		'utf8'
	);
	process.env.DISTRIBUTED_FAKE_LOG = log;
	const plugin = distributedSvelteKit({
		...pluginOptions(root, script),
		clients: [clients()[0]]
	});
	const started = Date.now();
	await assert.rejects(
		plugin.configResolved({ root }),
		/output exceeded 16777216 bytes/
	);
	assert.ok(Date.now() - started < 5_000, 'overflow kill is bounded');
	await plugin.closeBundle();
});

async function waitFor(predicate) {
	const deadline = Date.now() + 3_000;
	while (Date.now() < deadline) {
		if (await predicate()) return;
		await new Promise((resolve) => setTimeout(resolve, 10));
	}
	throw new Error('timed out waiting for fake compiler state');
}
