import assert from 'node:assert/strict';
import {
	mkdtemp,
	mkdir,
	readFile,
	rm,
	symlink,
	writeFile
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Worker } from 'node:worker_threads';
import test from 'node:test';

import {
	checkDistributedSvelteKit,
	distributedSvelteKit,
	distributedSvelteKitAliases,
	generateDistributedSvelteKit
} from '../dist/sveltekit/vite.js';

const fakeDctlSource = String.raw`
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  writeFileSync
} from 'node:fs';

const args = process.argv.slice(2);
appendFileSync(process.env.DISTRIBUTED_FAKE_LOG, JSON.stringify(args) + '\n');

if (args[0] === 'client-manifest') {
  process.stdout.write(JSON.stringify({ version: 7, source: args.at(-1) }));
  process.exit(0);
}

if (args[0] !== 'client') {
  process.stderr.write('unexpected fake command');
  process.exit(64);
}

const value = (name) => args[args.indexOf(name) + 1];
const surface = value('--surface') ?? value('--role');
if (surface === process.env.DISTRIBUTED_FAKE_FAIL_SURFACE) {
  process.stdout.write('sensitive schema and policy payload');
  process.stderr.write('synthetic compiler failure');
  process.exit(2);
}

const out = value('--out');
const documents = args.flatMap((arg, index) =>
  arg === '--documents' ? [args[index + 1]] : []
);
if (args.includes('--check')) {
  if (!existsSync(out + '/sveltekit.ts')) {
    process.stderr.write('missing generated entrypoint');
    process.exit(3);
  }
  process.stdout.write('fake client is current\n');
  process.exit(0);
}
const delay = Number(process.env.DISTRIBUTED_FAKE_DELAY_MS ?? 0);
if (delay > 0) await new Promise((resolve) => setTimeout(resolve, delay));
mkdirSync(out, { recursive: true });
writeFileSync(
  out + '/sveltekit.ts',
  '/** GENERATED by distributed client. Do not edit. */\nexport const surface = ' +
    JSON.stringify(surface) + ';\nexport const documents = ' +
    JSON.stringify(documents) + ';\n'
);
writeFileSync(
  out + '/manifest.json',
  JSON.stringify({ compiler_manifest_version: 1, operations: [] }) + '\n'
);
process.stdout.write('generated fake client\n');
`;

async function fixture(t) {
	const root = await mkdtemp(join(tmpdir(), 'distributed-vite-test-'));
	const script = join(root, 'fake-distributed.mjs');
	const log = join(root, 'commands.log');
	await writeFile(script, fakeDctlSource, 'utf8');
	await writeFile(log, '', 'utf8');
	await mkdir(join(root, 'src/routes/todos'), { recursive: true });
	await mkdir(join(root, 'src/routes/admin'), { recursive: true });
	await writeFile(
		join(root, 'src/routes/todos/+page.graphql'),
		'query Todos @load { todos { id } }\n'
	);
	await writeFile(
		join(root, 'src/routes/admin/+page.graphql'),
		'query AdminTodos @load { todos { id } }\n'
	);
	const previousLog = process.env.DISTRIBUTED_FAKE_LOG;
	const previousFailure = process.env.DISTRIBUTED_FAKE_FAIL_SURFACE;
	const previousDelay = process.env.DISTRIBUTED_FAKE_DELAY_MS;
	process.env.DISTRIBUTED_FAKE_LOG = log;
	delete process.env.DISTRIBUTED_FAKE_FAIL_SURFACE;
	delete process.env.DISTRIBUTED_FAKE_DELAY_MS;
	t.after(async () => {
		if (previousLog === undefined) delete process.env.DISTRIBUTED_FAKE_LOG;
		else process.env.DISTRIBUTED_FAKE_LOG = previousLog;
		if (previousFailure === undefined) {
			delete process.env.DISTRIBUTED_FAKE_FAIL_SURFACE;
		} else {
			process.env.DISTRIBUTED_FAKE_FAIL_SURFACE = previousFailure;
		}
		if (previousDelay === undefined) {
			delete process.env.DISTRIBUTED_FAKE_DELAY_MS;
		} else {
			process.env.DISTRIBUTED_FAKE_DELAY_MS = previousDelay;
		}
		await rm(root, { recursive: true, force: true });
	});
	return { root, script, log };
}

function clients() {
	return [
		{
			module: '$distributed',
			manifest: { args: ['client-manifest', '--entrypoint', 'user'] },
			surface: 'e2e-ui',
			documents: ['src/routes/todos/+page.graphql'],
			out: 'src/generated/user'
		},
		{
			module: '$distributed/admin',
			manifest: { args: ['client-manifest', '--entrypoint', 'admin'] },
			surface: 'e2e-ui-admin',
			documents: ['src/routes/admin/+page.graphql'],
			out: 'src/generated/admin'
		}
	];
}

function pluginOptions(root, script) {
	return {
		cwd: root,
		command: process.execPath,
		commandArgs: [script],
		clients: clients()
	};
}

async function commandLog(path) {
	const source = await readFile(path, 'utf8');
	return source
		.trim()
		.split('\n')
		.filter(Boolean)
		.map((line) => JSON.parse(line));
}

test('Vite compiles and resolves isolated user/admin physical entrypoints', async (t) => {
	const { root, script, log } = await fixture(t);
	const options = pluginOptions(root, script);
	const plugin = distributedSvelteKit(options);
	await plugin.configResolved({ root });

	const aliases = distributedSvelteKitAliases({
		cwd: root,
		clients: options.clients
	});
	assert.deepEqual(aliases, {
		'$distributed/admin': join(root, 'src/generated/admin/sveltekit.ts'),
		$distributed: join(root, 'src/generated/user/sveltekit.ts')
	});

	const userId = plugin.resolveId('$distributed');
	const adminId = plugin.resolveId('$distributed/admin');
	assert.match(userId, /^\0@hops-ops\/distributed:sveltekit:/);
	assert.match(adminId, /^\0@hops-ops\/distributed:sveltekit:/);
	assert.match(
		plugin.load(userId),
		new RegExp(
			JSON.stringify(join(root, 'src/generated/user/sveltekit.ts')).replace(
				/[.*+?^${}()|[\]\\]/g,
				'\\$&'
			)
		)
	);
	assert.match(
		await readFile(join(root, 'src/generated/admin/sveltekit.ts'), 'utf8'),
		/e2e-ui-admin/
	);

	const initial = await commandLog(log);
	assert.deepEqual(
		initial.map((args) => args[0]),
		['client-manifest', 'client', 'client-manifest', 'client']
	);
	assert.deepEqual(
		initial
			.filter((args) => args[0] === 'client')
			.map((args) => args[args.indexOf('--surface') + 1]),
		['e2e-ui', 'e2e-ui-admin']
	);

	const added = [];
	const messages = [];
	const invalidated = [];
	const modules = new Map([
		[userId, { id: userId }],
		[adminId, { id: adminId }]
	]);
	const server = {
		watcher: { add: (paths) => added.push(paths) },
		ws: { send: (message) => messages.push(message) },
		moduleGraph: {
			getModuleById: (id) => modules.get(id),
			invalidateModule: (module) => invalidated.push(module.id)
		}
	};
	plugin.configureServer(server);
	assert.ok(added.flat().some((path) => path.includes('src/routes/')));

	const change = {
		file: join(root, 'src/routes/todos/+page.graphql'),
		server
	};
	await Promise.all([
		plugin.handleHotUpdate(change),
		plugin.handleHotUpdate(change),
		plugin.handleHotUpdate(change)
	]);
	const afterChanges = await commandLog(log);
	assert.equal(
		afterChanges.length,
		12,
		'three overlapping notifications coalesce into one active and one trailing transaction'
	);
	assert.deepEqual(invalidated, [userId, adminId]);
	assert.equal(
		messages.filter((message) => message.type === 'full-reload').length,
		1,
		'one successful coalesced generation issues one full reload'
	);
	assert.equal(
		await plugin.handleHotUpdate({
			file: join(root, 'src/generated/user/ignored.graphql'),
			server
		}),
		undefined,
		'generated output changes never trigger the compiler'
	);
	await plugin.closeBundle();

	const beforeCheck = await readFile(
		join(root, 'src/generated/user/sveltekit.ts'),
		'utf8'
	);
	await checkDistributedSvelteKit(options);
	assert.equal(
		await readFile(join(root, 'src/generated/user/sveltekit.ts'), 'utf8'),
		beforeCheck,
		'the shared check runner never rewrites generated output'
	);
	await generateDistributedSvelteKit(options);
	assert.match(
		await readFile(join(root, 'src/generated/user/sveltekit.ts'), 'utf8'),
		/todos/
	);
});

test('same-process Vite instances coalesce one shared startup generation', async (t) => {
	const { root, script, log } = await fixture(t);
	process.env.DISTRIBUTED_FAKE_DELAY_MS = '75';
	const options = pluginOptions(root, script);
	const first = distributedSvelteKit(options);
	const second = distributedSvelteKit(options);

	await Promise.all([
		first.configResolved({ root }),
		second.configResolved({ root })
	]);
	assert.deepEqual(
		(await commandLog(log)).map((args) => args[0]),
		[
			'client-manifest',
			'client',
			'client-manifest',
			'client'
		],
		'identical plugin instances compile one startup generation'
	);

	await first.closeBundle();
	await second.watchChange(join(root, 'src/routes/todos/+page.graphql'));
	assert.equal(
		(await commandLog(log)).length,
		8,
		'the remaining instance retains the shared project lock'
	);
	await second.closeBundle();
	await checkDistributedSvelteKit(options);
});

test('SvelteKit config-probe workers never compile or contend for the project lock', async (t) => {
	const { root, script, log } = await fixture(t);
	const options = pluginOptions(root, script);
	const moduleUrl = new URL('../dist/sveltekit/vite.js', import.meta.url).href;
	const resolved = await new Promise((resolvePromise, rejectPromise) => {
		const worker = new Worker(
			String.raw`
const { parentPort, workerData } = require('node:worker_threads');
(async () => {
  const { distributedSvelteKit } = await import(workerData.moduleUrl);
  const plugin = distributedSvelteKit(workerData.options);
  await plugin.configResolved({ root: workerData.options.cwd });
  const resolved = plugin.resolveId('$distributed');
  await plugin.closeBundle();
  parentPort.postMessage({ resolved });
})().catch((error) => {
  parentPort.postMessage({ error: error?.stack ?? String(error) });
});
`,
			{
				eval: true,
				env: { ...process.env, SVELTEKIT_FORK: 'true' },
				workerData: { moduleUrl, options }
			}
		);
		worker.once('message', (message) => {
			if (message?.error !== undefined) {
				rejectPromise(new Error(message.error));
			} else {
				resolvePromise(message.resolved);
			}
		});
		worker.once('error', rejectPromise);
	});

	assert.match(resolved, /^\0@hops-ops\/distributed:sveltekit:/);
	assert.deepEqual(await commandLog(log), []);
});

test('multi-surface failure leaves old outputs intact and redacts stdout', async (t) => {
	const { root, script } = await fixture(t);
	const userOut = join(root, 'src/generated/user');
	const adminOut = join(root, 'src/generated/admin');
	await mkdir(userOut, { recursive: true });
	await mkdir(adminOut, { recursive: true });
	await writeFile(join(userOut, 'sveltekit.ts'), 'old-user\n');
	await writeFile(join(adminOut, 'sveltekit.ts'), 'old-admin\n');
	process.env.DISTRIBUTED_FAKE_FAIL_SURFACE = 'e2e-ui-admin';

	const plugin = distributedSvelteKit(pluginOptions(root, script));
	await assert.rejects(
		plugin.configResolved({ root }),
		(error) => {
			assert.match(error.message, /synthetic compiler failure/);
			assert.match(error.message, /argv: \[/);
			assert.match(error.message, new RegExp(`cwd: ${root}`));
			assert.doesNotMatch(error.message, /sensitive schema and policy payload/);
			return true;
		}
	);
	assert.equal(await readFile(join(userOut, 'sveltekit.ts'), 'utf8'), 'old-user\n');
	assert.equal(
		await readFile(join(adminOut, 'sveltekit.ts'), 'utf8'),
		'old-admin\n'
	);
	await plugin.closeBundle();
});

test('configuration rejects ambiguous surfaces, aliases, and output containment hazards', async (t) => {
	const { root, script } = await fixture(t);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					...clients(),
					{
						...clients()[0],
						module: '$distributed/nested',
						out: 'src/generated/user/nested'
					}
				]
			}),
		/outputs must not overlap/
	);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					{
						...clients()[0],
						surface: 'e2e-ui',
						role: 'user'
					}
				]
			}),
		/exactly one of role or surface/
	);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [clients()[0], { ...clients()[1], module: '$distributed' }]
			}),
		/duplicate Distributed client module/
	);

	const outside = await mkdtemp(join(tmpdir(), 'distributed-vite-outside-'));
	t.after(() => rm(outside, { recursive: true, force: true }));
	await symlink(outside, join(root, 'linked-output'));
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					{
						...clients()[0],
						out: 'linked-output/user'
					}
				]
			}),
		/contains symlink component|resolves outside project root/,
		'language-tool aliases reject an escaping symlink before Vite starts'
	);
	const plugin = distributedSvelteKit({
		...pluginOptions(root, script),
		clients: [
			{
				...clients()[0],
				out: 'linked-output/user'
			}
		]
	});
	await assert.rejects(
		plugin.configResolved({ root }),
		/contains symlink component|resolves outside project root/
	);
	await plugin.closeBundle();

	await mkdir(join(root, 'src/generated/shared'), { recursive: true });
	await symlink(
		join(root, 'src/generated/shared'),
		join(root, 'src/generated/shared-alias')
	);
	assert.throws(
		() =>
			distributedSvelteKitAliases({
				cwd: root,
				clients: [
					{ ...clients()[0], out: 'src/generated/shared/user' },
					{
						...clients()[1],
						out: 'src/generated/shared-alias/user'
					}
				]
			}),
		/contains symlink component|physically overlap/,
		'two lexical outputs cannot alias one physical authorization surface'
	);
});

test('gql changes regenerate and cancellation before commit preserves old outputs', async (t) => {
	const { root, script, log } = await fixture(t);
	const options = pluginOptions(root, script);
	const plugin = distributedSvelteKit(options);
	await plugin.configResolved({ root });
	const server = {
		watcher: { add() {} },
		ws: { send() {} },
		moduleGraph: {
			getModuleById: () => undefined,
			invalidateModule() {}
		}
	};
	const gql = join(root, 'src/routes/todos/extra.gql');
	await writeFile(gql, 'query Extra { todos { id } }\n');
	const beforeGql = (await commandLog(log)).length;
	await plugin.handleHotUpdate({ file: gql, server });
	assert.equal(
		(await commandLog(log)).length,
		beforeGql + 4,
		'legacy .gql inputs receive the same compiler watch lifecycle'
	);
	await plugin.closeBundle();

	const userOut = join(root, 'src/generated/user');
	const adminOut = join(root, 'src/generated/admin');
	await writeFile(join(userOut, 'sveltekit.ts'), 'stable-user\n');
	await writeFile(join(adminOut, 'sveltekit.ts'), 'stable-admin\n');
	process.env.DISTRIBUTED_FAKE_DELAY_MS = '5000';
	const cancelling = distributedSvelteKit(options);
	const startup = cancelling.configResolved({ root });
	await waitFor(async () => (await commandLog(log)).at(-1)?.[0] === 'client');
	await cancelling.closeBundle();
	await assert.rejects(startup);
	assert.equal(
		await readFile(join(userOut, 'sveltekit.ts'), 'utf8'),
		'stable-user\n'
	);
	assert.equal(
		await readFile(join(adminOut, 'sveltekit.ts'), 'utf8'),
		'stable-admin\n'
	);
});

test('overflowing compiler output is bounded and force-killed', async (t) => {
	const { root, log } = await fixture(t);
	const script = join(root, 'overflow.mjs');
	await writeFile(
		script,
		`process.on('SIGTERM', () => {});\n` +
			`const chunk = 'x'.repeat(1024 * 1024);\n` +
			`for (let i = 0; i < 20; i += 1) process.stdout.write(chunk);\n` +
			`setInterval(() => {}, 1000);\n`,
		'utf8'
	);
	process.env.DISTRIBUTED_FAKE_LOG = log;
	const plugin = distributedSvelteKit({
		...pluginOptions(root, script),
		clients: [clients()[0]]
	});
	const started = Date.now();
	await assert.rejects(
		plugin.configResolved({ root }),
		/output exceeded 16777216 bytes/
	);
	assert.ok(Date.now() - started < 5_000, 'overflow kill is bounded');
	await plugin.closeBundle();
});

async function waitFor(predicate) {
	const deadline = Date.now() + 3_000;
	while (Date.now() < deadline) {
		if (await predicate()) return;
		await new Promise((resolve) => setTimeout(resolve, 10));
	}
	throw new Error('timed out waiting for fake compiler state');
}
