//! Raw Kubernetes/Knative and offline Hops XR renderers.
//!
//! Every target consumes the same [`ResolvedDeployment`]. Target-specific YAML
//! is derived. Each target also emits a parseable `DeploymentInventory`
//! document so inventories are compared from shipped files, not from the
//! in-memory resolver twice.

use super::error::{ApplicationError, ApplicationResult};
use super::resolve::ResolvedDeployment;
use super::topology::TopologyIntent;

/// Render target supported by the portable compiler.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RenderTarget {
    Kubernetes,
    Knative,
    HopsXr,
}

impl RenderTarget {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Kubernetes => "kubernetes",
            Self::Knative => "knative",
            Self::HopsXr => "hops-xr",
        }
    }

    pub fn parse(value: &str) -> Result<Self, ApplicationError> {
        match value {
            "kubernetes" => Ok(Self::Kubernetes),
            "knative" => Ok(Self::Knative),
            "hops-xr" => Ok(Self::HopsXr),
            other => Err(ApplicationError::InvalidSpec(format!(
                "unsupported render target `{other}`"
            ))),
        }
    }
}

/// One rendered file for a target.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RenderedFile {
    pub path: String,
    pub contents: String,
}

/// Render the resolved graph for one target. Does not apply to a cluster.
pub fn render_resolved(
    resolved: &ResolvedDeployment,
    target: RenderTarget,
) -> ApplicationResult<Vec<RenderedFile>> {
    match target {
        RenderTarget::Kubernetes => Ok(vec![RenderedFile {
            path: "deploy/kubernetes.yaml".into(),
            contents: render_kubernetes(resolved),
        }]),
        RenderTarget::Knative => Ok(vec![RenderedFile {
            path: "deploy/knative.yaml".into(),
            contents: render_knative(resolved),
        }]),
        RenderTarget::HopsXr => Ok(vec![RenderedFile {
            path: "deploy/distributed-application.yaml".into(),
            contents: render_hops_xr(resolved),
        }]),
    }
}

fn yaml_quote(value: &str) -> String {
    value.replace('\'', "''")
}

fn render_inventory_document(resolved: &ResolvedDeployment) -> String {
    let inventory = normalize_resolved(resolved);
    let mut out = String::new();
    out.push_str("apiVersion: distributed.dev/v1\n");
    out.push_str("kind: DeploymentInventory\n");
    out.push_str(&format!(
        "metadata:\n  name: '{name}'\n  labels:\n    distributed.inventory: '{digest}'\nspec:\n  application: '{app}'\n  plan: '{plan}'\n  digest: '{digest}'\n",
        name = yaml_quote(&inventory.application),
        app = yaml_quote(&inventory.application),
        plan = yaml_quote(&inventory.plan),
        digest = yaml_quote(&inventory.digest),
    ));
    push_yaml_list(&mut out, "  processes:", &inventory.processes);
    push_yaml_list(&mut out, "  mounts:", &inventory.mounts);
    push_yaml_list(&mut out, "  routes:", &inventory.routes);
    push_yaml_list(&mut out, "  subscriptions:", &inventory.subscriptions);
    push_yaml_list(&mut out, "  capabilities:", &inventory.capabilities);
    out
}

fn push_yaml_list(out: &mut String, header: &str, items: &[String]) {
    out.push_str(header);
    out.push('\n');
    if items.is_empty() {
        out.push_str("    []\n");
        return;
    }
    for item in items {
        out.push_str("    - '");
        out.push_str(&yaml_quote(item));
        out.push_str("'\n");
    }
}

fn render_kubernetes(resolved: &ResolvedDeployment) -> String {
    let mut out = String::new();
    out.push_str("# generated by distributed deployment render --target kubernetes\n");
    out.push_str(&render_inventory_document(resolved));
    for process in &resolved.processes {
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str("---\n");
        out.push_str(&format!(
            "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: '{name}'\n  labels:\n    app.kubernetes.io/name: '{app}'\n    app.kubernetes.io/component: '{name}'\n    distributed.plan: '{plan}'\n    distributed.inventory: '{digest}'\nspec:\n  selector:\n    matchLabels:\n      app.kubernetes.io/component: '{name}'\n  template:\n    metadata:\n      labels:\n        app.kubernetes.io/component: '{name}'\n    spec:\n      containers:\n        - name: '{name}'\n          image: 'application:plan'\n          env:\n            - name: DISTRIBUTED_PROCESS\n              value: '{name}'\n            - name: DISTRIBUTED_PLAN\n              value: '{plan}'\n",
            name = yaml_quote(&process.id),
            app = yaml_quote(&resolved.application),
            plan = yaml_quote(&resolved.plan),
            digest = yaml_quote(&resolved.inventory_digest),
        ));
    }
    out
}

fn render_knative(resolved: &ResolvedDeployment) -> String {
    let mut out = String::new();
    out.push_str("# generated by distributed deployment render --target knative\n");
    out.push_str(&render_inventory_document(resolved));
    for process in &resolved.processes {
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str("---\n");
        out.push_str(&format!(
            "apiVersion: serving.knative.dev/v1\nkind: Service\nmetadata:\n  name: '{name}'\n  labels:\n    app.kubernetes.io/name: '{app}'\n    distributed.plan: '{plan}'\n    distributed.inventory: '{digest}'\nspec:\n  template:\n    spec:\n      containers:\n        - image: 'application:plan'\n          env:\n            - name: DISTRIBUTED_PROCESS\n              value: '{name}'\n",
            name = yaml_quote(&process.id),
            app = yaml_quote(&resolved.application),
            plan = yaml_quote(&resolved.plan),
            digest = yaml_quote(&resolved.inventory_digest),
        ));
        for intent in &process.topology {
            if let TopologyIntent::CommandRoute {
                command_id,
                remote,
                ..
            } = intent
            {
                if *remote {
                    out.push_str(&format!(
                        "            - name: DISTRIBUTED_REMOTE_COMMAND\n              value: '{command}'\n",
                        command = yaml_quote(command_id),
                    ));
                }
            }
        }
    }
    out
}

fn render_hops_xr(resolved: &ResolvedDeployment) -> String {
    let inventory = normalize_resolved(resolved);
    let mut out = String::new();
    out.push_str("# generated by distributed deployment render --target hops-xr\n");
    out.push_str(&render_inventory_document(resolved));
    out.push_str("---\n");
    out.push_str("apiVersion: apps.hops.dev/v1alpha1\n");
    out.push_str("kind: DistributedApplication\n");
    out.push_str(&format!(
        "metadata:\n  name: '{name}'\nspec:\n  artifact:\n    manifestDigest: '{manifest}'\n    planDigest: '{plan}'\n    inventoryDigest: '{inventory}'\n  inventory:\n    processes:\n",
        name = yaml_quote(&resolved.application),
        manifest = yaml_quote(&resolved.application_manifest_canonical),
        plan = yaml_quote(&resolved.plan_canonical),
        inventory = yaml_quote(&resolved.inventory_digest),
    ));
    for process in &inventory.processes {
        out.push_str(&format!("      - '{name}'\n", name = yaml_quote(process)));
    }
    out.push_str("    mounts:\n");
    for mount in &inventory.mounts {
        out.push_str(&format!("      - '{mount}'\n", mount = yaml_quote(mount)));
    }
    out.push_str("    routes:\n");
    for route in &inventory.routes {
        out.push_str(&format!("      - '{route}'\n", route = yaml_quote(route)));
    }
    out.push_str("    subscriptions:\n");
    for subscription in &inventory.subscriptions {
        out.push_str(&format!(
            "      - '{subscription}'\n",
            subscription = yaml_quote(subscription)
        ));
    }
    out.push_str("    capabilities:\n");
    for capability in &inventory.capabilities {
        out.push_str(&format!(
            "      - '{capability}'\n",
            capability = yaml_quote(capability)
        ));
    }
    out.push_str("  processes:\n");
    for process in &resolved.processes {
        out.push_str(&format!(
            "    - name: '{name}'\n      mounts:\n",
            name = yaml_quote(&process.id)
        ));
        if process.mounts.is_empty() {
            out.push_str("        []\n");
            continue;
        }
        for mount in &process.mounts {
            out.push_str(&format!(
                "        - kind: {kind}\n          id: '{id}'\n",
                kind = mount.kind_label(),
                id = yaml_quote(mount.id()),
            ));
        }
    }
    out
}

/// Parse the shared inventory document from a rendered target file.
///
/// Looks for `kind: DeploymentInventory` and reads the emitted spec lists.
/// This is the conformance extractor: tests compare these parsed values, not
/// a second in-memory `normalize_resolved` call.
pub fn inventory_from_rendered(yaml: &str) -> ApplicationResult<NormalizedInventory> {
    let document = yaml
        .split("\n---\n")
        .chain(std::iter::once(yaml))
        .find(|chunk| chunk.contains("kind: DeploymentInventory"))
        .ok_or_else(|| {
            ApplicationError::InvalidSpec(
                "rendered YAML does not contain a DeploymentInventory document".into(),
            )
        })?;
    let application = yaml_scalar(document, "application:")?;
    let plan = yaml_scalar(document, "plan:")?;
    let digest = yaml_scalar(document, "digest:")?;
    Ok(NormalizedInventory {
        application,
        plan,
        processes: yaml_list(document, "processes:")?,
        mounts: yaml_list(document, "mounts:")?,
        routes: yaml_list(document, "routes:")?,
        subscriptions: yaml_list(document, "subscriptions:")?,
        capabilities: yaml_list(document, "capabilities:")?,
        digest,
    })
}

fn yaml_scalar(document: &str, key: &str) -> ApplicationResult<String> {
    for line in document.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix(key) {
            return Ok(unquote(rest.trim()));
        }
    }
    Err(ApplicationError::InvalidSpec(format!(
        "inventory document missing `{key}`"
    )))
}

fn yaml_list(document: &str, key: &str) -> ApplicationResult<Vec<String>> {
    let mut lines = document.lines().peekable();
    while let Some(line) = lines.next() {
        if !line.trim_start().starts_with(key) {
            continue;
        }
        if line.trim_end().ends_with("[]") {
            return Ok(Vec::new());
        }
        let mut items = Vec::new();
        while let Some(next) = lines.peek() {
            let trimmed = next.trim_start();
            if let Some(item) = trimmed.strip_prefix("- ") {
                items.push(unquote(item.trim()));
                lines.next();
            } else if trimmed.is_empty() {
                lines.next();
            } else {
                break;
            }
        }
        return Ok(items);
    }
    Err(ApplicationError::InvalidSpec(format!(
        "inventory document missing list `{key}`"
    )))
}

fn unquote(value: &str) -> String {
    let value = value.trim();
    if let Some(inner) = value.strip_prefix('\'').and_then(|v| v.strip_suffix('\'')) {
        return inner.replace("''", "'");
    }
    if let Some(inner) = value.strip_prefix('"').and_then(|v| v.strip_suffix('"')) {
        return inner.to_string();
    }
    value.to_string()
}

/// Normalized inventory used for cross-renderer conformance.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizedInventory {
    pub application: String,
    pub plan: String,
    pub processes: Vec<String>,
    pub mounts: Vec<String>,
    pub routes: Vec<String>,
    pub subscriptions: Vec<String>,
    pub capabilities: Vec<String>,
    pub digest: String,
}

/// Extract the shared semantic inventory from a resolved graph.
pub fn normalize_resolved(resolved: &ResolvedDeployment) -> NormalizedInventory {
    let mut processes = resolved
        .processes
        .iter()
        .map(|process| process.id.clone())
        .collect::<Vec<_>>();
    processes.sort();
    let mut mounts = Vec::new();
    let mut routes = Vec::new();
    let mut subscriptions = Vec::new();
    for process in &resolved.processes {
        for mount in &process.mounts {
            mounts.push(format!("{}:{}", process.id, mount.id()));
        }
        for intent in &process.topology {
            match intent {
                TopologyIntent::CommandRoute { command_id, .. } => {
                    routes.push(format!("{}:{}", process.id, command_id));
                }
                TopologyIntent::ProjectionSubscription { projection_id, .. } => {
                    subscriptions.push(format!("{}:{}", process.id, projection_id));
                }
                TopologyIntent::SurfaceEndpoint { surface_id, .. } => {
                    routes.push(format!("{}:surface:{}", process.id, surface_id));
                }
                TopologyIntent::ExtensionHook { extension_id, .. } => {
                    routes.push(format!("{}:extension:{}", process.id, extension_id));
                }
            }
        }
    }
    mounts.sort();
    routes.sort();
    subscriptions.sort();
    let mut capabilities = resolved
        .capabilities
        .iter()
        .map(|requirement| requirement.capability.as_str().to_string())
        .collect::<Vec<_>>();
    capabilities.sort();
    capabilities.dedup();
    NormalizedInventory {
        application: resolved.application.clone(),
        plan: resolved.plan.clone(),
        processes,
        mounts,
        routes,
        subscriptions,
        capabilities,
        digest: resolved.inventory_digest.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::application::{
        compile_deployment_plan, resolve_deployment, Application, CommandDefinition, CommandSpec,
        CommandTypeSpec, ModelFieldSpec, ModelSpec, Module, ProcessIntent, ProcessPreset,
        ProjectionSpec,
    };
    use crate::graphql::CommandConsistency;

    fn sample() -> (crate::application::ApplicationManifest, crate::application::DeploymentPlan) {
        let model = ModelSpec::try_new(
            "TodoView",
            "todos",
            [ModelFieldSpec {
                name: "todo_id".into(),
                scalar: "String".into(),
                nullable: false,
            }],
            ["todo_id"],
        )
        .unwrap();
        let command = CommandSpec::try_new(
            "todo.create",
            "todo_create",
            CommandTypeSpec {
                name: "In".into(),
                fields: vec![],
            },
            CommandTypeSpec {
                name: "Out".into(),
                fields: vec![],
            },
            CommandConsistency::Eventual,
        )
        .unwrap();
        let module = Module::new("todo")
            .command_definitions([CommandDefinition::contract(command)])
            .models([model])
            .projections([
                ProjectionSpec::try_new("project_todos", ["todo.created"], ["TodoView"]).unwrap(),
            ])
            .build()
            .unwrap();
        let manifest = Application::new("todo-app")
            .module(module)
            .build()
            .unwrap()
            .manifest()
            .clone();
        let plan = compile_deployment_plan(
            "split",
            &manifest,
            [
                ProcessIntent::with_preset("writer", &manifest, ProcessPreset::Writer).unwrap(),
                ProcessIntent::with_preset("projector", &manifest, ProcessPreset::Projector)
                    .unwrap(),
            ],
        )
        .unwrap();
        (manifest, plan)
    }

    #[test]
    fn one_pair_local_realization_and_renderers_share_parsed_inventory() {
        use crate::application::{CapabilityProviders, RuntimeHost};
        use crate::command_dispatch::{CommandDispatchError, CommandDispatcher};
        use crate::microsvc::{CommandRequest, CommandResponse};
        use async_trait::async_trait;
        use std::sync::Arc;

        struct Stub;
        #[async_trait]
        impl CommandDispatcher for Stub {
            async fn dispatch(
                &self,
                _request: &CommandRequest,
            ) -> Result<CommandResponse, CommandDispatchError> {
                Ok(CommandResponse {
                    status: 200,
                    body: serde_json::json!({}),
                })
            }
            fn kind(&self) -> &'static str {
                "stub"
            }
        }

        let (manifest, plan) = sample();
        let resolved = resolve_deployment(&manifest, &plan).unwrap();
        let expected = normalize_resolved(&resolved);

        let mut providers = CapabilityProviders::default();
        for requirement in &plan.capabilities {
            providers = providers.with(requirement.capability);
        }
        let dispatcher = Arc::new(Stub) as crate::command_dispatch::SharedCommandDispatcher;
        let writer = RuntimeHost::bind(
            &plan,
            "writer",
            providers.clone(),
            Some(Arc::clone(&dispatcher)),
        )
        .unwrap();
        let projector = RuntimeHost::bind(&plan, "projector", providers, Some(dispatcher)).unwrap();
        assert_eq!(writer.process_id(), "writer");
        assert_eq!(projector.process_id(), "projector");
        let from_hosts = crate::application::inventory_from_hosts(&resolved, &[&writer, &projector]);
        assert_eq!(from_hosts, expected, "local realization inventory");

        let k8s = render_resolved(&resolved, RenderTarget::Kubernetes).unwrap();
        let knative = render_resolved(&resolved, RenderTarget::Knative).unwrap();
        let xr = render_resolved(&resolved, RenderTarget::HopsXr).unwrap();
        let from_k8s = inventory_from_rendered(&k8s[0].contents).unwrap();
        let from_knative = inventory_from_rendered(&knative[0].contents).unwrap();
        let from_xr = inventory_from_rendered(&xr[0].contents).unwrap();
        assert_eq!(from_k8s, expected, "kubernetes inventory from YAML");
        assert_eq!(from_knative, expected, "knative inventory from YAML");
        assert_eq!(from_xr, expected, "hops-xr inventory from YAML");
        assert!(k8s[0].contents.contains("kind: Deployment"));
        assert!(knative[0].contents.contains("serving.knative.dev"));
        assert!(xr[0].contents.contains("kind: DistributedApplication"));
        assert!(xr[0].contents.contains("kind: command") || xr[0].contents.contains("kind: projector"));
        assert!(!xr[0].contents.contains("Projector {"));
        assert!(from_k8s.processes.contains(&"writer".to_string()));
        assert!(from_k8s.processes.contains(&"projector".to_string()));
        assert!(from_k8s.mounts.iter().any(|mount| mount.contains("todo.create")));
    }

    #[test]
    fn resolve_rejects_stale_plan_predecessor() {
        let (manifest, mut plan) = sample();
        plan.application_manifest_canonical = "sha256:stale".into();
        let error = resolve_deployment(&manifest, &plan).unwrap_err().to_string();
        assert!(
            error.contains("predecessor") || error.contains("stale") || error.contains("fingerprint"),
            "{error}"
        );
    }
}
