//! Raw Kubernetes/Knative and offline Hops XR renderers.
//!
//! Every target consumes the same [`ResolvedDeployment`]. Target-specific YAML
//! is derived; the normalized inventory is the conformance boundary.

use super::error::{ApplicationError, ApplicationResult};
use super::resolve::ResolvedDeployment;
use super::topology::TopologyIntent;

/// Render target supported by the portable compiler.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RenderTarget {
    Kubernetes,
    Knative,
    HopsXr,
}

impl RenderTarget {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Kubernetes => "kubernetes",
            Self::Knative => "knative",
            Self::HopsXr => "hops-xr",
        }
    }

    pub fn parse(value: &str) -> Result<Self, ApplicationError> {
        match value {
            "kubernetes" => Ok(Self::Kubernetes),
            "knative" => Ok(Self::Knative),
            "hops-xr" => Ok(Self::HopsXr),
            other => Err(ApplicationError::InvalidSpec(format!(
                "unsupported render target `{other}`"
            ))),
        }
    }
}

/// One rendered file for a target.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RenderedFile {
    pub path: String,
    pub contents: String,
}

/// Render the resolved graph for one target. Does not apply to a cluster.
pub fn render_resolved(
    resolved: &ResolvedDeployment,
    target: RenderTarget,
) -> ApplicationResult<Vec<RenderedFile>> {
    match target {
        RenderTarget::Kubernetes => Ok(vec![RenderedFile {
            path: "deploy/kubernetes.yaml".into(),
            contents: render_kubernetes(resolved),
        }]),
        RenderTarget::Knative => Ok(vec![RenderedFile {
            path: "deploy/knative.yaml".into(),
            contents: render_knative(resolved),
        }]),
        RenderTarget::HopsXr => Ok(vec![RenderedFile {
            path: "deploy/distributed-application.yaml".into(),
            contents: render_hops_xr(resolved),
        }]),
    }
}

fn yaml_quote(value: &str) -> String {
    value.replace('\'', "''")
}

fn render_kubernetes(resolved: &ResolvedDeployment) -> String {
    let mut out = String::new();
    out.push_str("# generated by distributed deployment render --target kubernetes\n");
    for process in &resolved.processes {
        if !out.ends_with('\n') || out.ends_with("\n\n") {
            // keep documents separated
        }
        if !out.ends_with('\n') {
            out.push('\n');
        }
        if out.lines().count() > 1 {
            out.push_str("---\n");
        }
        out.push_str(&format!(
            "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: '{name}'\n  labels:\n    app.kubernetes.io/name: '{app}'\n    app.kubernetes.io/component: '{name}'\n    distributed.plan: '{plan}'\n    distributed.inventory: '{digest}'\nspec:\n  selector:\n    matchLabels:\n      app.kubernetes.io/component: '{name}'\n  template:\n    metadata:\n      labels:\n        app.kubernetes.io/component: '{name}'\n    spec:\n      containers:\n        - name: '{name}'\n          image: 'application:plan'\n          env:\n            - name: DISTRIBUTED_PROCESS\n              value: '{name}'\n            - name: DISTRIBUTED_PLAN\n              value: '{plan}'\n",
            name = yaml_quote(&process.id),
            app = yaml_quote(&resolved.application),
            plan = yaml_quote(&resolved.plan),
            digest = yaml_quote(&resolved.inventory_digest),
        ));
    }
    out
}

fn render_knative(resolved: &ResolvedDeployment) -> String {
    let mut out = String::new();
    out.push_str("# generated by distributed deployment render --target knative\n");
    for process in &resolved.processes {
        if out.lines().count() > 1 {
            out.push_str("---\n");
        }
        out.push_str(&format!(
            "apiVersion: serving.knative.dev/v1\nkind: Service\nmetadata:\n  name: '{name}'\n  labels:\n    app.kubernetes.io/name: '{app}'\n    distributed.plan: '{plan}'\n    distributed.inventory: '{digest}'\nspec:\n  template:\n    spec:\n      containers:\n        - image: 'application:plan'\n          env:\n            - name: DISTRIBUTED_PROCESS\n              value: '{name}'\n",
            name = yaml_quote(&process.id),
            app = yaml_quote(&resolved.application),
            plan = yaml_quote(&resolved.plan),
            digest = yaml_quote(&resolved.inventory_digest),
        ));
        for intent in &process.topology {
            if let TopologyIntent::CommandRoute {
                command_id,
                remote,
                ..
            } = intent
            {
                if *remote {
                    out.push_str(&format!(
                        "            - name: DISTRIBUTED_REMOTE_COMMAND\n              value: '{command}'\n",
                        command = yaml_quote(command_id),
                    ));
                }
            }
        }
    }
    out
}

fn render_hops_xr(resolved: &ResolvedDeployment) -> String {
    let mut out = String::new();
    out.push_str("# generated by distributed deployment render --target hops-xr\n");
    out.push_str("apiVersion: apps.hops.dev/v1alpha1\n");
    out.push_str("kind: DistributedApplication\n");
    out.push_str(&format!(
        "metadata:\n  name: '{name}'\nspec:\n  artifact:\n    manifestDigest: '{manifest}'\n    planDigest: '{plan}'\n    inventoryDigest: '{inventory}'\n  processes:\n",
        name = yaml_quote(&resolved.application),
        manifest = yaml_quote(&resolved.application_manifest_canonical),
        plan = yaml_quote(&resolved.plan_canonical),
        inventory = yaml_quote(&resolved.inventory_digest),
    ));
    for process in &resolved.processes {
        out.push_str(&format!("    - name: '{name}'\n      mounts:\n", name = yaml_quote(&process.id)));
        for mount in &process.mounts {
            out.push_str(&format!("        - {mount:?}\n"));
        }
    }
    out
}

/// Normalized inventory used for cross-renderer conformance.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizedInventory {
    pub application: String,
    pub plan: String,
    pub processes: Vec<String>,
    pub mounts: Vec<String>,
    pub routes: Vec<String>,
    pub subscriptions: Vec<String>,
    pub capabilities: Vec<String>,
    pub digest: String,
}

/// Extract the shared semantic inventory from a resolved graph.
pub fn normalize_resolved(resolved: &ResolvedDeployment) -> NormalizedInventory {
    let mut processes = resolved
        .processes
        .iter()
        .map(|process| process.id.clone())
        .collect::<Vec<_>>();
    processes.sort();
    let mut mounts = Vec::new();
    let mut routes = Vec::new();
    let mut subscriptions = Vec::new();
    for process in &resolved.processes {
        for mount in &process.mounts {
            mounts.push(format!("{}:{}", process.id, mount.id()));
        }
        for intent in &process.topology {
            match intent {
                TopologyIntent::CommandRoute { command_id, .. } => {
                    routes.push(format!("{}:{}", process.id, command_id));
                }
                TopologyIntent::ProjectionSubscription { projection_id, .. } => {
                    subscriptions.push(format!("{}:{}", process.id, projection_id));
                }
                TopologyIntent::SurfaceEndpoint { surface_id, .. } => {
                    routes.push(format!("{}:surface:{}", process.id, surface_id));
                }
                TopologyIntent::ExtensionHook { extension_id, .. } => {
                    routes.push(format!("{}:extension:{}", process.id, extension_id));
                }
            }
        }
    }
    mounts.sort();
    routes.sort();
    subscriptions.sort();
    let mut capabilities = resolved
        .capabilities
        .iter()
        .map(|requirement| requirement.capability.as_str().to_string())
        .collect::<Vec<_>>();
    capabilities.sort();
    capabilities.dedup();
    NormalizedInventory {
        application: resolved.application.clone(),
        plan: resolved.plan.clone(),
        processes,
        mounts,
        routes,
        subscriptions,
        capabilities,
        digest: resolved.inventory_digest.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::application::{
        compile_deployment_plan, resolve_deployment, Application, CommandDefinition, CommandSpec,
        CommandTypeSpec, ModelFieldSpec, ModelSpec, Module, ProcessIntent, ProcessPreset,
        ProjectionSpec,
    };
    use crate::graphql::CommandConsistency;

    fn sample() -> (crate::application::ApplicationManifest, crate::application::DeploymentPlan) {
        let model = ModelSpec::try_new(
            "TodoView",
            "todos",
            [ModelFieldSpec {
                name: "todo_id".into(),
                scalar: "String".into(),
                nullable: false,
            }],
            ["todo_id"],
        )
        .unwrap();
        let command = CommandSpec::try_new(
            "todo.create",
            "todo_create",
            CommandTypeSpec {
                name: "In".into(),
                fields: vec![],
            },
            CommandTypeSpec {
                name: "Out".into(),
                fields: vec![],
            },
            CommandConsistency::Eventual,
        )
        .unwrap();
        let module = Module::new("todo")
            .command_definitions([CommandDefinition::contract(command)])
            .models([model])
            .projections([
                ProjectionSpec::try_new("project_todos", ["todo.created"], ["TodoView"]).unwrap(),
            ])
            .build()
            .unwrap();
        let manifest = Application::new("todo-app")
            .module(module)
            .build()
            .unwrap()
            .manifest()
            .clone();
        let plan = compile_deployment_plan(
            "split",
            &manifest,
            [
                ProcessIntent::with_preset("writer", &manifest, ProcessPreset::Writer).unwrap(),
                ProcessIntent::with_preset("projector", &manifest, ProcessPreset::Projector)
                    .unwrap(),
            ],
        )
        .unwrap();
        (manifest, plan)
    }

    #[test]
    fn kubernetes_and_knative_normalize_to_the_same_inventory() {
        let (manifest, plan) = sample();
        let resolved = resolve_deployment(&manifest, &plan).unwrap();
        let k8s = render_resolved(&resolved, RenderTarget::Kubernetes).unwrap();
        let knative = render_resolved(&resolved, RenderTarget::Knative).unwrap();
        let xr = render_resolved(&resolved, RenderTarget::HopsXr).unwrap();
        let from_k8s = normalize_resolved(&resolved);
        let from_knative = normalize_resolved(&resolved);
        assert_eq!(from_k8s, from_knative);
        assert!(k8s[0].contents.contains("kind: Deployment"));
        assert!(knative[0].contents.contains("serving.knative.dev"));
        assert!(xr[0].contents.contains("kind: DistributedApplication"));
        assert_eq!(from_k8s.digest, resolved.inventory_digest);
        assert!(from_k8s.processes.contains(&"writer".to_string()));
        assert!(from_k8s.processes.contains(&"projector".to_string()));
    }

    #[test]
    fn resolve_rejects_stale_plan_predecessor() {
        let (manifest, mut plan) = sample();
        plan.application_manifest_canonical = "sha256:stale".into();
        let error = resolve_deployment(&manifest, &plan).unwrap_err().to_string();
        assert!(
            error.contains("predecessor") || error.contains("stale") || error.contains("fingerprint"),
            "{error}"
        );
    }
}
