name: Rust Quality Pipeline for PRs

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: unbounded-tech/workflows-rust/.github/workflows/quality.yaml@feat/cargo-publish
    with:
      cargo_build_args: "--verbose"
      cargo_test_args: "--verbose"
      cargo_incremental: true
